### ISSUE TITLE
set_transform() behavior with Points and non-Points

### ISSUE THREAD

**Issue by LucaMarconato** [scverse/spatialdata#101]
`set_transform()` can't modify `pyarrow.Table` in-place (`Points`), so it returns a copy of it, where the transformation is put in the metadata (this is an efficient operation as no real copy of the data is made, all is passed by references). In contrast, `set_transform()` currently modify the transformation in-place for the rest of the spatial elements.

Since it is not possible to modify the `pyarrow.Table` in-place, maybe we should make the behavior for the other spatial element follow the one for the `Points`. But if we stop using parquet, then this problem disappear and we can modify the transformation in-place everywhere.

**Comment by giovp** [comment]
this should be addressed by #113
