### ISSUE TITLE
modules import hierarchy

### ISSUE THREAD

**Issue by giovp** [scverse/spatialdata#103]
right now, basically every module can be import from spatialdata main module.

e.g. this works:
```python
from spatialdata import SpatialData, Scale, Image2DModel
```

I think it's a bit confusing and I think something like this would be clearer
```python
from spatialdata import Spatialdata
from spatialdata.models import Image2DModel
from spatialdata.transforms import Scale
```

ideas? @scverse/spatialdata

**Comment by LucaMarconato** [comment]
I agree with you, I think the above approach is a good one. Only thing to pay attention is that need to split the imports from `spatialdata._core.core_utils` into the appropriate modules.

**Comment by LucaMarconato** [comment]
Notes:
* `->` indicates a renaming of the currently used nomenclature
* functions/classes that are not listed here, are not public. The one here needs to be in the docs.

# spatialdata

- SpatialData
- read_zarr
- concatenate
- get_dims -> get_axis_names

# spatialdata.transform

- BaseTransformation
- Identity
- MapAxis
- Translation
- Scale
- Affine
- Sequence
- set_transform
- get_transform
- remove_transform
- get_transformation_between_coordinate_systems
- get_transformation_between_landmakrs
- align_elements_using_landmarks

# spatialdata.models

- Labels2DModel
- Labels3DModel
- Image2DModel
- Image3DModel
- PolygonsModel
- ShapesModel
- PointsModel
- TableModel
- get_schema -> get_model

# spatialdata.aggregation

- aggregate_numerical_annotations
- aggregate_categorical_annotations
- aggregate_elements

# spatialdata.query

- bounding_box_query(element: SpatialElement, min_coordinate: ArrayLike, max_coordinate: ArrayLike, coordinate_system: str)

# spatialdata.element_utils

- unpad_raster
- get_table_mapping_metadata

**Comment by giovp** [comment]
sounds good, couple of other things to change to keep track of:
- I would still add an `io` module for readers, writers and format.
- I would still keep spatialdata and models in `_core`
- I would be consistent with `utils.py` file across repo (e.g. always private `_utils.py` and also not stuff like `core_utils.py`

**Comment by giovp** [comment]
pinging @scverse/spatialdata for comments here since this is quite important and should be done by end of this week imhop

**Comment by LucaMarconato** [comment]
> I would still keep spatialdata and models in _core

Basically an empty package `models` whose `__init__.py` imports from `spatialdata._core.models`?

**Comment by LucaMarconato** [comment]
Also let's remember to change the folders of the tests to mirror the new code structure.

**Comment by LucaMarconato** [comment]
I am also going to remove the method `.transform()` from the class `BaseTransformation` and make it an external method. In this way the file `transformation.py` will be independent from `SpatialData` and `SpatialElement`, making the code more compartmentalized. This also mimics what we do for `query()`, `rasterize()` and `aggregate()`.

**Comment by giovp** [comment]
> I am also going to remove the method `.transform()` from the class `BaseTransformation` and make it an external method. In this way the file `transformation.py` will be independent from `SpatialData` and `SpatialElement`, making the code more compartmentalized. This also mimics what we do for `query()`, `rasterize()` and `aggregate()`.

fantastic, this should be changed also for notebooks then. Before this though #145 will be merged correct?

**Comment by LucaMarconato** [comment]
yes, already merged
