### ISSUE TITLE
Wrong usage of `to_multiscale()` and automatic creating of the levels

### ISSUE THREAD

**Issue by LucaMarconato** [scverse/spatialdata#108]
@giovp not sure if you were where aware (I was not), but `to_multiscale(image, [2, 4])` creates a multiscale with levels `[original, original / 2, original / 8]`, and not `[original, original / 2, original / 4]`. For performance I think it is better to divide by 2 the dims all the time instead of having larger jumps in dimension.

To this regard, I wonder if we should implement a default behavior for the multiscale object so that the user, unless wanted, doesn't have to specify the scalefactors automatically.

I would implement the following logic:
```
shape = data.shape
SCALE_FACTOR = 2
MIN_CHUNK_SIZE = 100
for n in shape:
    if n < max(shape) / SCALE_FACTOR or n < MIN_CHUNK_SIZE:
        # leave the dimension intact
    else:
        # divide the dimension by SCALE_FACTOR
```

In the case in which the shape is made of dimensions with comparable values, like (1024, 1024, 1000), this would basically divide the dimensions by SCALE_FACTOR at each level of the pyramid.

**Comment by LucaMarconato** [comment]
Asking also feedback to @kevinyamauchi regarding a reasonable choice of scale factors for obtaining a useful image pyramid.

**Comment by LucaMarconato** [comment]
When applying crops, rotations, etc we need to decide to:
1) either apply this at each level of the pyramid independently;
2) either to apply it to the higher level and then reconstructing the image pyramid. 

If we go for option 1, not only we need to have a method to automatically creating the levels of the image pyramid, but I would even remove the option for the use to create them, because after the first transformation they would change anyway.

I prefer the option 1, because with some transformations (e.g. upscaling or stretching of the axes, the new chunkings and multiscale levels could be non-optimal). Also we make the life easier for the users.

**Comment by giovp** [comment]
I think rather than default behaviour (I don't think we know what's good heuristic yet) having the warning/error check directly in `spatial-image` would be better (as discussed in other issue). 

> I prefer the option 1, because with some transformations (e.g. upscaling or stretching of the axes, the new chunkings and multiscale levels could be non-optimal). Also we make the life easier for the users.

from this reasoning I understand option 2? I think option 2 would be an easier solution.

**Comment by LucaMarconato** [comment]
Yeah thinking better about it my reasoning doesn't really support one of the other case... let's think more about it. I need to change the implementation of some functions to use the approach 2 since I have applied something to the large image and then created the levels. Gonna change that or mark the code as code to be changed.
