### ISSUE TITLE
Detecting collapsed dimensions when calling `to_multiscale()`

### ISSUE THREAD

**Issue by LucaMarconato** [scverse/spatialdata#110]
At the moment if the user passes scaling factors that are too large when parsing an array into a `MultiscaleSpatialImage`, this could lead to collapsing some dimensions to zero.
For instance this is an example of `scalefactors=[2, 4]` for a `zyx` image that was initially 10x148x148:

```
[array([ 10, 148, 148]), array([ 5, 74, 74]), array([0, 7, 7])]
```

We should detect cases like this because they propagate into bugs.
Alternatives:
- [ ] we call `to_multiscale()` in parser and then we remove those levels of the pyramid that are invalid
- [ ] we predict the invalid levels before calling `to_multiscale()`, we raise a warning and we remove them from the call (I have implemented this at the moment)

The code to check the scaling factors could also be moved in `multiscale_spatial_image` (@thewtex what do you think)?

**Comment by LucaMarconato** [comment]
If `scale_factors` is a list I use this simple code:
```
# check that the image pyramid doesn't contain axes that get collapsed and eventually truncates the list
# of downscaling factors to avoid this
adjusted_multiscale_factors = []
current_shape = np.array(data.shape, dtype=float)
for factor in multiscale_factors:
    current_shape /= float(factor)
    if current_shape.min() < 1:
        logger.warning(
            "Detected a multiscale factor that would collapse an axis: truncating list of factors from "
            f"{multiscale_factors} to {adjusted_multiscale_factors}"
        )
        break
    adjusted_multiscale_factors.append(factor)
data = to_multiscale(
    data,
    scale_factors=adjusted_multiscale_factors,
    method=method,
    chunks=chunks,
)
```

**Comment by thewtex** [comment]
> we predict the invalid levels before calling to_multiscale(), we raise a warning and we remove them from the call (I have implemented this at the moment)

@LucaMarconato agreed! This is a good approach. I think elevating the warning to an error could even be warranted.

> this could lead to collapsing some dimensions to zero

Another, stricter practical constraint I have ran into: if a shape's length is smaller than the dask chunk length in a given dimension, dask can crash. This means we may need to constrain both the scale factors and the chunk length at the highest scale.

> The code to check the scaling factors could also be moved in multiscale_spatial_image (@thewtex what do you think)?

:+1: :100:

**Comment by giovp** [comment]
fantastic, I'll open a PR to `spatial-image` to catch those cases later this week!

**Comment by LucaMarconato** [comment]
Thanks a lot for the feedbacks!
