### ISSUE TITLE
Refinements to the schema for `MultiscaleSpatialImage`

### ISSUE THREAD

**Issue by LucaMarconato** [scverse/spatialdata#115]
Here is how a `MultiscaleSpatialImage` looks like
```
DataTree('None', parent=None)
├── DataTree('scale0')
│       Dimensions:             (c: 3, y: 64, x: 64)
│       Dimensions without coordinates: c, y, x
│       Data variables:
│           image2d_multiscale  (c, y, x) float64 dask.array<chunksize=(3, 64, 64), meta=np.ndarray>
└── DataTree('scale1')
        Dimensions:             (c: 3, y: 32, x: 32)
        Dimensions without coordinates: c, y, x
        Data variables:
            image2d_multiscale  (c, y, x) float64 dask.array<chunksize=(3, 32, 32), meta=np.ndarray>
```
and this is an example of the second level of the multiscale
```
data['scale1']['image2d_multiscale']
Out[4]: 
<xarray.DataArray 'image2d_multiscale' (c: 3, y: 32, x: 32)>
dask.array<mean_agg-aggregate, shape=(3, 32, 32), dtype=float64, chunksize=(3, 32, 32), chunktype=numpy.ndarray>
Dimensions without coordinates: c, y, x
Attributes:
    transform:  Sequence \n    Scale (y, x)\n        [2. 2.]\n    Identity 
```

We need to add the following constraints to the validator:
1) the nodes of the tree are only 'scale0', 'scale1', etc.
2) each node has only one data variable (`image2d_multiscale` in the example above). The name is irrelevant
3) each data variable has the transformation in `.attrs['transform']`. That is, the transformation is not here: `multiscale_data.attrs['transform']`; it's not here: `multiscale_data.attrs['scale0'].attrs['transform']`, but it's here: `multiscale_data.attrs['scale0']['image2d_multiscale'].attrs['transform']`.

Right now this type of validation is scattered around the repo. In particular this is done in `write.py`, in the function `_iter_multiscale()`, here reported
```
def _iter_multiscale(
    data: MultiscaleSpatialImage,
    attr: str,
    key: Optional[str] = None,
) -> list[Any]:
    # TODO: put this check also in the validator for raster multiscales
    name = None
    for i in data.keys():
        variables = list(data[i].variables)
        if len(variables) != 1:
            raise ValueError("MultiscaleSpatialImage must have exactly one variable (the variable name is arbitrary)")
        if name is not None:
            if name != variables[0]:
                raise ValueError("MultiscaleSpatialImage must have the same variable name across all levels")
        name = variables[0]
    if key is None:
        return [getattr(data[i][name], attr) for i in data.keys()]
    else:
        return [getattr(data[i][name], attr).get(key) for i in data.keys()]
```
and it is done in `get_transform()` from `core_utils.py`:
```
    d = dict(e['scale0'])
    assert len(d) == 1
    xdata = d.values().__iter__().__next__()
    t = get_transform(xdata)
```

**Comment by LucaMarconato** [comment]
For the moment I remove completely the `attrs` constraint in the validator (`RasterSchema`). In fact this would be valid only for `SpatialImage`, not for `MultiscaleSpatialImage`.

**Comment by giovp** [comment]
agree on everything. I will wait for transform to get merged and update it.

**Comment by giovp** [comment]
> 1. the nodes of the tree are only 'scale0', 'scale1', etc.

done
> 2. each node has only one data variable (`image2d_multiscale` in the example above). The name is irrelevant

done
> 3. each data variable has the transformation in `.attrs['transform']`. That is, the transformation is not here: `multiscale_data.attrs['transform']`; it's not here: `multiscale_data.attrs['scale0'].attrs['transform']`, but it's here: `multiscale_data.attrs['scale0']['image2d_multiscale'].attrs['transform']`.

I think this can still be validated with xarray-schema, will check and remove the comment if so.
