### ISSUE TITLE
Dealing with transformations between extrinsic coordinate systems

### ISSUE THREAD

**Issue by LucaMarconato** [scverse/spatialdata#121]
@kevinyamauchi @giovp @ivirshup 

Sometimes we have transformations between extrinsic coordinate systems. Here are my thoughts about supporting them.

Consider the dataset `cosmx` from `spatialdata-sandbox`. 
* It contains 20 fields of view that are crops of a global one.
* Each field of view contains and image element, a labels element and a points element. 
* For each field of view we have a coordinate systems, say `fov10`, that contains the respective elements.

### Approach 0a (only transformations intrinsic -> extrinsic)
Currently each element of the field of view has an `Affine` transformation (the same for all the elements of the fov), that if applied, aligns the various fov together. In other words we have this.
```
assert image0.attrs[TRANFORM_KEY] == {'fov0: affine0, 'global': affine0}
assert labels0.attrs[TRANFORM_KEY] == {'fov0: affine0, 'global': affine0}
assert points0.attrs[TRANFORM_KEY] == {'fov0: affine0, 'global': affine0}

assert image1.attrs[TRANFORM_KEY] == {'fov1: affine1, 'global': affine1}
assert labels1.attrs[TRANFORM_KEY] == {'fov1: affine1, 'global': affine1}
assert points1.attrs[TRANFORM_KEY] == {'fov1: affine1, 'global': affine1}

...
```
### Approach 1a (only transformations intrinsic -> extrinsic)
The approach above is not the only one, the user could decide to do the following (that I find more natural):
```
assert image0.attrs[TRANFORM_KEY] == {'fov0: identity, 'global': affine0}
assert labels0.attrs[TRANFORM_KEY] == {'fov0: identity, 'global': affine0}
assert points0.attrs[TRANFORM_KEY] == {'fov0: identity, 'global': affine0}

assert image1.attrs[TRANFORM_KEY] == {'fov1: identity, 'global': affine1}
assert labels1.attrs[TRANFORM_KEY] == {'fov1: identity, 'global': affine1}
assert points1.attrs[TRANFORM_KEY] == {'fov1: identity, 'global': affine1}

...
```
### Approach 0b (both intrinsic -> extrinsic and extrinsic -> extrinsic transformations)
If extrinsic -> extrinsic transformations were allowed, the approach 0a would be equivalent to the following:
```
assert image0.attrs[TRANFORM_KEY] == {'fov0: affine0}
assert labels0.attrs[TRANFORM_KEY] == {'fov0: affine0}
assert points0.attrs[TRANFORM_KEY] == {'fov0: affine0}

assert image1.attrs[TRANFORM_KEY] == {'fov1: affine1}
assert labels1.attrs[TRANFORM_KEY] == {'fov1: affine1}
assert points1.attrs[TRANFORM_KEY] == {'fov1: affine1}

...

# also stored somewhere the transformations
# 'fov0' -> 'global' via identity
# 'fov1' -> 'global' via identity
# ...
```

### Approach 1b (both intrinsic -> extrinsic and extrinsic -> extrinsic transformations)
Similarly, the approach 1a would be equivalent to the following:
```
assert image0.attrs[TRANFORM_KEY] == {'fov0: identity}
assert labels0.attrs[TRANFORM_KEY] == {'fov0: identity}
assert points0.attrs[TRANFORM_KEY] == {'fov0: identity}

assert image1.attrs[TRANFORM_KEY] == {'fov1: identity}
assert labels1.attrs[TRANFORM_KEY] == {'fov1: identity}
assert points1.attrs[TRANFORM_KEY] == {'fov1: identity}

...

# also stored somewhere the transformations
# 'fov0' -> 'global' via affine0
# 'fov1' -> 'global' via affine1
# ...
```

### Negative implications of approach 1b
The approach 1b, which is very natural and for sure would happen if we support extrinsic -> extrinsic transfomations, has a negative implication. 
Say that we are in napari, and we want to visualize what is inside the `global` space. What we do is that we can compute the directed graph of transformations and find that all the elements are in the `global` space, correct.

But now if we want to visualize the space `fov0`, we would also find that all the elements are in the `fov0` space! Since fov0 -> image0 -> global -> image1.

In other words, without the restrictions that transformations are only between intrinsic and extrinsic coordinate systems, we can't use the coordinate systems as "views"/"collections" of the data to define what belongs together (like labels0 and image0 are "living together"). We would need an additional "collection specification". Furthermore, the example above is very easy, but we could quickly end up with mutliple paths between different elements, making it impossible to unambiguously map elements together without further verbosity.

### Solution
I though about this and I realized that intrinsic -> extrinsic transformations are powerful enough to conveniently cover the use cases of extrinsic -> extrinsic transformations. In fact, I can easily modify (basically I have done already in a notebook) the method (`class SpatialData`)

```
    def set_transformation(
        self,
        element: SpatialElement,
        transformation: BaseTransformation,
        target_coordinate_system: Optional[str] = None,
    ) -> None:
        """
        Set/replace a transformation of an element, writing it to disk if the SpatialData object is backed.

        Parameters
        ----------
        element
            The element to replace the transformation for.
        transformation
            The new transformation.
        target_coordinate_system
            The target coordinate system of the transformation. If None, the default coordinate system is used.

        Notes
        -----
        - You can also use the static method SpatialData.set_transformation_in_memory() to set the transformation of an
        element when it is not backed
        """
```

as follows

```
    def set_transformation(
        self,
        source: Union[SpatialElement, str],
        transformation: BaseTransformation,
        target: Union[SpatialElement, str],
    ) -> None:
```
This would operate like this:
1. `source: SpatialElement`, `target: str`: same as the current implementation
2. `source: str`, `target: SpatialElement`:, if the transformation can be inverted, calls the case 1., otherwise throws an exception.
3. `source: SpatialElement`, `target: SpatialElement`: error, not supported
4. `source: str, target: str`. For each element that has a transformation `t` that maps it to `source`, add the following transformation `Sequence([t, transformation])` to map to `target`.

**Comment by giovp** [comment]
thanks @LucaMarconato about the clear explanation. Couple of points:
- while I understand the various options, I think they are not covering other use cases like: `intrinsic -> global -> global 3D -> another global`. It seems to me that the examples you posed are mostly about how to think about the intrinsic-extrinsic (with identity or not) rather than generalize to extrinsic-extrinsic
- The sequence is indeed powerful enough to build the case above as `intrinsic -> another global`. We'd loose the intermediate cs though which could be otherwise useful to build a DAG and hence infer the best path for the sequence.

My 2 cents for now are is that your solution should work for now but I think we might want to be more explicit about coordinate systems in the future

**Comment by LucaMarconato** [comment]
Thanks for the comment (and the tag trick 😁), I will keep thinking about this. For the moment indeed the approach above is very low effort to implement, but we can go back to this.

**Comment by LucaMarconato** [comment]
Closing as duplicate of the "coordinate transformation refactoring" issue, which would lead to the resolution of the current one. https://github.com/scverse/spatialdata/issues/308
