### ISSUE TITLE
Building a `MultiscaleSpatialImage` from a `DataTree`, and getting the dimensions

### ISSUE THREAD

**Issue by LucaMarconato** [scverse/spatialdata#150]
FYI @thewtex and @giovp.
In this issue I discuss a use case where I feel the ergonomics could be improved on a few points (that I highlight in italics). Or maybe I am doing something suboptimal with my code, so I would ask you for feedback.

I am performing a cropping operation on a `MultiscaleSpatialImage` object with `image.sel(...)`. What this returns is a `DataTree`. I would like to build a `MultiscaleSpatialImage` object this `DataTree`.

What I am doing is calling something like `MultiscaleSpatialImage.from_dict(d={'scale0': xdata0, 'scale1': xadata1, ...})`.
*I think that the ergonomics could be improved by having a method to initialize such an object.*

Now, the returned `MultiscaleSpatialImage` looks like this:

```python console
In[27]: msi
Out[27]: 
DataTree('None', parent=None)
├── DataTree('scale0')
│       Dimensions:             (y: 148, x: 148, c: 3)
│       Coordinates:
│         * y                   (y) float64 0.0 1.0 2.0 3.0 ... 144.0 145.0 146.0 147.0
│         * x                   (x) float64 0.0 1.0 2.0 3.0 ... 144.0 145.0 146.0 147.0
│       Dimensions without coordinates: c
│       Data variables:
│           image2d_multiscale  (c, y, x) float64 dask.array<chunksize=(3, 64, 64), meta=np.ndarray>
├── DataTree('scale1')
│       Dimensions:             (y: 74, x: 74, c: 3)
│       Coordinates:
│         * y                   (y) float64 0.5 2.5 4.5 6.5 ... 140.5 142.5 144.5 146.5
│         * x                   (x) float64 0.5 2.5 4.5 6.5 ... 140.5 142.5 144.5 146.5
│       Dimensions without coordinates: c
│       Data variables:
│           image2d_multiscale  (c, y, x) float64 dask.array<chunksize=(3, 32, 32), meta=np.ndarray>
└── DataTree('scale2')
        Dimensions:             (y: 37, x: 37, c: 3)
        Coordinates:
          * y                   (y) float64 1.5 5.5 9.5 13.5 ... 133.5 137.5 141.5 145.5
          * x                   (x) float64 1.5 5.5 9.5 13.5 ... 133.5 137.5 141.5 145.5
        Dimensions without coordinates: c
        Data variables:
            image2d_multiscale  (c, y, x) float64 dask.array<chunksize=(3, 16, 16), meta=np.ndarray>
```
As you can see, the dimensions from the `DataTree` look like `(y: 148, x: 148, c: 3)`, which lead to `list(msi['scale0].dims.keys())`  being `['y', 'x', 'c']`.
On the contrary if we look inside the data, like at `msi['scale0']['image2d_multiscale'].dims` we obtain `('c', 'y', 'x')`. In our case this difference led to a subtle bug in the code and now we look only at the latter. But I wonder if this is the desired behavior, or if when constructing a `MultiscaleSpatialImage` object from a `DataTree` we would instead prefer to have the dimensions of each scale equal to the dimensions of the data.

**Comment by melonora** [comment]
closing this as I don't think it is longer relevant with direct support of `DataTree` in `multiscale-spatial-image`, but feel free to reopen if not the case.
