### ISSUE TITLE
Model.type

### ISSUE THREAD

**Issue by ivirshup** [scverse/spatialdata#152]
@giovp, could the `Model` classes get a class attribute which holds the in-memory types they can be?

Then I could write things like:

```
def aggregate(
    values: PointsModel.type | ShapeModel.type | Image2DModel.type,
    by: ShapeModel.type | Label2DModel.type | Label3DModel.type,
    ...
)

**Comment by giovp** [comment]
think it could yes! 

Otherwise something like this? https://github.com/scverse/spatialdata/blob/38c661c75be8ed76f6bc2906eb5c4664ce43dbc1/spatialdata/_core/core_utils.py#L22

**Comment by ivirshup** [comment]
I would prefer that the types elements can be is defined in one place. Since the model already needs this info, I think it's a reasonable place to put it.

**Comment by melonora** [comment]
Perhaps for people implementing `SpatialData` in their libraries?

**Comment by melonora** [comment]
closing this but feel free to reopen
