### ISSUE TITLE
IO tests

### ISSUE THREAD

**Issue by giovp** [scverse/spatialdata#16]
Write solid IO tests, few considerations that come to mind from current implementation:
- right now, if a label is in it's own group, without an image, it won't be read. Would we want to keep it like this or would we allow to store plain Labels objects without images?
- there is no IO for Transform at all (although ome_zarr support this, yet helper classes will be needed to convert what we store in `Transform` class to the ome specs)
- `Points` are saved as anndata but:
  - there is no distinction between visium or transcript type of points.
  - there is no consensus on the additional metadata that should be stored with it (will open separate issue).

**Comment by LucaMarconato** [comment]
> right now, if a label is in it's own group, without an image, it won't be read. Would we want to keep it like this or would we allow to store plain Labels objects without images?

I would allow also labels on their own, I needed this in my code in the past.

> there is no IO for Transform at all (although ome_zarr support this, yet helper classes will be needed to convert what we store in Transform class to the ome specs)

pushing something within a few hours with that implemented.

> Points are saved as anndata but:
there is no distinction between visium or transcript type of points.
there is no consensus on the additional metadata that should be stored with it (will open separate issue).

I need to think about it.

**Comment by kevinyamauchi** [comment]
We split out our io to `spatialdata-io` and added tests where applicable here. I will close for now. Please feel free to re-open if you deem it necessary.
