### ISSUE TITLE
repr is extremely slow

### ISSUE THREAD

**Issue by ivirshup** [scverse/spatialdata#171]
Displaying the repr for a spatial data object with points is extremely slow (20 seconds for me), with most of the time being consumed by calculating the length of the points dataframe. I think should consider just not including the number of points in the repr if its going to be this expensive.

**Comment by LucaMarconato** [comment]
Related to this: https://github.com/scverse/spatialdata/issues/140 and this: https://github.com/scverse/spatialdata/pull/141.

Before the PR the repr was omitting to print the length.

**Comment by LucaMarconato** [comment]
I agree to omit the length from the repr, unless the points are backed, in that case we can read the length from the parquet file instantly.
