### ISSUE TITLE
Construction pattern

### ISSUE THREAD

**Issue by giovp** [scverse/spatialdata#18]
copying from comment from @kevinyamauchi 

### Construction pattern
What is our preferred construction pattern for a SpatialData object when the data are already in memory (i.e., not from an OME-NGFF file)? Should the user first create Element objects (e.g., Image, Labels and then pass those to the SpatialData constructor? Or should they pass some more basic objects (e.g., numpy arrays) directly to the SpatialData constructor and then the constructor does coercion/construction into our Element types?

Personally, I would prefer that for now, we require the user to construct the Element objects and then pass those to the SpatialData constructor. I think we should not implement too much coercion for now, as allowing multiple types and inferring how to coerce them always adds complexity. We can always add convenience functions later, but for now, I think we should focus on making the core solid.

**Comment by LucaMarconato** [comment]
I would also go for being explicit. This is also the approach we were using for spatialmuon [here](https://github.com/ilia-kats/spatialmuon/blob/202202_graphs/spatialmuon/datasets/visium_mousebrain.py). Since the repo is private I post the relevant code also here.

```
    smudata = spatialmuon.SpatialMuData(outfname, backingmode="w")
    smudata["Visium"] = modality = spatialmuon.SpatialModality()
    # ....
    anchor = spatialmuon.Anchor(vector=np.array([center_to_center / 100, 0.0]))

    labels = obs.index.tolist()
    masks = ShapeMasks(
        masks_shape="circle", masks_centers=coords, masks_radii=radius, masks_labels=labels
    )

    cfov = spatialmuon.Regions(
        X=X, var=var, masks=masks, anchor=anchor, coordinate_unit="um"
    )
    modality[fovname] = cfov

    img = Image.open(os.path.join(cdir, "spatial", "tissue_hires_image.png"))
    hires_img = np.asarray(img)
    img.close()
    modality[f"{fovname}H&E"] = spatialmuon.Raster(
        X=hires_img, anchor=anchor, coordinate_unit="um"
      )
```

The old `Anchor` is now `Transform`, the old `ShapeMasks` is not points, and `Regions` is now "annotated" `Points`.

**Comment by LucaMarconato** [comment]
But in the future I would try to make the constructor more ergonomic for the user, by implementing some convenient data coercion and do all the job in 1-2 function calls.
