### ISSUE TITLE
Type coercion for Image/Labels

### ISSUE THREAD

**Issue by giovp** [scverse/spatialdata#20]
various comments from @kevinyamauchi 

> type coercion: for now, I think we should avoid automatically converting too many input types. In general, I find that it adds bloat and can often lead to odd behaviors due to the implicit assumptions that inevitably made. We can add helper conversion functions in the future once we understand the main pathways.

> For loading OME-NGFF from disk, I think we can/should do the type coercion because we know exactly how to do it (thanks to the specification). The point I was trying to make is that I want to avoid "automagical" type coercion in the SpatialData and Element constructors for now because it generally requires implicit assumptions about the input data. For example, in the test below, what is the coordinate space and what are the axis names for "image"

another note (but maybe to be discussed in new issue) is how to handle multiscale, and whether we should prioritize at all (yes imho).

**Comment by LucaMarconato** [comment]
Closing as this is the implemented behavior: the constructor of `SpatialData` doesn't coerce types and it just calls the validation functions.
