### ISSUE TITLE
Recommended defaults for `region_key` and `instance_key`

### ISSUE THREAD

**Issue by LucaMarconato** [scverse/spatialdata#212]
I like the defaults `region_key` = `region` and `instance_key` = `instance_id`. I think we should"
- [x] use these in spatialdata-io
- [ ] write this suggestion in the design doc (recommended naming).

**Comment by lopollar** [comment]
I would love it if there were even more default names: 
- default names for shapes layers: for example nucleus boundaries, cell boundaries
- points layers: call it transcripts or transcript locations?
- Same for images and masks. This will make it easier to reuse code!

**Comment by LucaMarconato** [comment]
Thanks for the feedback. There are cases in which the name we give is to reflect the names in the data formats from the vendors. But we will try to make these names more uniform to not confuse the user.

**Comment by LucaMarconato** [comment]
Done here: https://github.com/scverse/spatialdata/pull/630.

We opted not to use default names for other instances since, with some exceptions (e.g. Xenium) we tend to maintain the names given by the companies when reading their data, and these are highly heterogeneous.
