### ISSUE TITLE
semi-edgecase error for `filter_by_coordinate_system`

### ISSUE THREAD

**Issue by timtreis** [scverse/spatialdata#224]
Noticed in my unit test.

Assume a situation in which you want to subset a spatialdata object by one of its coordinate system keys. This could be achieved with

```
sdata.filter_by_coordinate_system("my_key") # sets filter_table=True by default
```

However, internally this function then goes on to automatically filter with

```
if filter_table:
    table_mapping_metadata = self.table.uns[TableModel.ATTRS_KEY]
```

Therefore, in the absence of a table and no further parameters specified, the default causes an error that is hard to trace. It'd be nice if the function could make the `if filter_table` check dependent on the presence of a table.

**Comment by kevinyamauchi** [comment]
Closing as I think this is fixed now: https://github.com/scverse/spatialdata/blob/ae616663daca83c56b2a7f1f97c80787618ec527/src/spatialdata/_core/query/relational_query.py#L17-L24
