### ISSUE TITLE
Tutorial, tests and parser argument for channel names in images

### ISSUE THREAD

**Issue by LucaMarconato** [scverse/spatialdata#230]
1. [ ] Create a tutorial or add documentation on how to use channel names with xarray images.
2. [x] Add tests for the channel naming functionality in xarray images.
3. [x] Consider adding an argument to the parser to allow users to easily add channel names when the input is not an xarray image, but something like a numpy image. -> the argument is `c_coords`

**Comment by LucaMarconato** [comment]
Related, a user just wrote:

> One question did anything change regarding the channel names when working with xarray? I used to be able to do spatialImage.sel(c="DAPI") for example but not anymore. When doing spatialImage.coords only x and y are returned now.

FYI @giovp

**Comment by LucaMarconato** [comment]
@quentinblampey here is a screenshot that shows the usage

![image](https://user-images.githubusercontent.com/2664412/233184544-84a593d0-116b-46d1-9cdd-6b76d54531e9.png)

Could you try to see if it works?

**Comment by LucaMarconato** [comment]
@giovp is `c_coords` an xarray parameter? I think we should document it in the docs for the image models.

**Comment by LucaMarconato** [comment]
@melonora can you reproduce the above example? If you do `import spaitaldata; print(spatialdata.__path__)` what do you get? Maybe the editable install got overridden by the install from a satellite package and you are using an old version.

**Comment by melonora** [comment]
I can reproduce the example. When I print the path I get the location in site-packages

**Comment by melonora** [comment]
Just to note with saving the example above I can read it into a spatialdata object again and then access the channels the usual way:
![image](https://user-images.githubusercontent.com/22346363/233291399-f74b6dcf-7f2e-4165-be96-53dfa403fdd6.png)

**Comment by giovp** [comment]
hi all, the way channel metadata is supposed to be saved in ome-zarr is currently broken upstream, hence decided for that solution. Once I fix it upstream then we'll just be using the way ome-zarr does it.

**Comment by melonora** [comment]
so the data can be kept in the way of using the omero part of the ome-ngff spec? As in this will be ultimately supported again?

**Comment by LucaMarconato** [comment]
> When I print the path I get the location in site-packages

I think then you are not using the latest dev version of `spatialdata` as if you do an editable install it should show the repo path. You can fix this by uninstalling the library, and reinstalling it again with `pip install -e .`. Note that if you run `pip install -e .` on any of the following: `spatialdata-io`, `napari-spatialdata`, `spatialdata-plot`, it will override the editable installation of `spatialdata` with a non editable one.

**Comment by melonora** [comment]
yeah someone changed the environment while I was on holiday. 

Question is reading the channel metadata done by ome-zarr or is it dealt with by SpatialData? In the latter case would it be possible to support both behaviours for now?

**Comment by melonora** [comment]
just checking the code in raster-io:) will get back to this topic
