### ISSUE TITLE
release to conda-forge

### ISSUE THREAD

**Issue by kevinyamauchi** [scverse/spatialdata#252]
As mentioned in https://github.com/scverse/napari-spatialdata/issues/67, it would be nice to distribute via conda-forge. I can have a look to see how easy that will be (haven't checked availability of deps on conda-forge).

**Comment by kevinyamauchi** [comment]
I had a look at our deps and it looks like `spatial-image` and `multiscale-spatial-image` are the only dependencies currently not available via conda-forge. I've made a request over there to see if we can help put those up on conda-forge. Should be straight forward after that.

https://github.com/spatial-image/spatial-image/issues/18

**Comment by LucaMarconato** [comment]
There were some dependencies conflicts that have now been resolved so today a new conda release is available. 

@FloWuenne for the moment the conda-forge system is setup and we have limited time so I'd prefer not to try bioconda. Anyway, we could have a job to build the docker container manually.
