### ISSUE TITLE
Option to save columns in shapes layer

### ISSUE THREAD

**Issue by lopollar** [scverse/spatialdata#311]
I think this was mentioned before, but I couldn't find it back.
When adding columns with annotation to the shapes layer, these aren't saved. 
I have different types of shapes I like to add, where all of them are labeled. 
I now have to save them as all separate shapes layer, but one shapes layer with an annotation column would be cleaner. 
Is this an option for the future?

**Comment by LucaMarconato** [comment]
Hi Lotte, thanks for reporting. We are soon going to improve the IO in a major refactoring and we will make sure that this is possible. You can see the progress of the refactoring here https://github.com/scverse/spatialdata/issues/293 (I think it will take a few weeks, please be patient).

**Comment by EliHei2** [comment]
I think it would be great to have the flexibility to add more columns to the shepes' geopandas dataframes, this is super useful, as sometimes having shapes that are not already in the table, one needs to associate some metadata to them. Having two versions segmentation masks for cells, and annotating them is one example. Obviously, one can add columns to the gdfs when in memory, but writing and reading again it doesn't load the added columns.
