### ISSUE TITLE
IndexError on raw greyscale arrays from multi-channel TIFF

### ISSUE THREAD

**Issue by matt-sd-watson** [scverse/spatialdata#313]
I am receiving this error when I attempt to read my numpy array into an `Image2DModel`: 

```
np.arange(data.shape[2], dtype=np.float64) * scale["x"] + translation["x"],
IndexError: tuple index out of range
```

The array shape is something like `(600, 600)` from a greyscale multi-channel TIFF. 

The error clears up if I first convert this array to RGB. 

If there a method to avoid this error when attempting to import greyscale/binary arrays into the model, and/or if this a design choice to require RGB arrays for SpatialData?

**Comment by LucaMarconato** [comment]
Hi @matt-sd-watson, I didn't understand exactly the problem, could you please post a complete runnable code example? Looks like a part of the code snipped you sent got cut out.

**Comment by matt-sd-watson** [comment]
Sorry about that, here is a minimal example. 

When I read in a multi-channel tiff to separate each tiff channel into its own array as below:

```
import spatialdata
from spatialdata.models import Image2DModel, TableModel
import numpy as np
from tifffile import TiffFile
from PIL import Image

tiff_path = "path_to_multi_channel_tiff.tiff"

image_dict = {}
with TiffFile(tiff_path) as tif:
    tiff_path = Path(tiff_path)
    multi_channel_index = 1
    for page in tif.pages:
        identifier = str("channel_" + str(multi_channel_index))
        image_dict[identifier] = Image2DModel().parse(data=page.asarray())
        multi_channel_index += 1

spatial_object = spatialdata.SpatialData(images=image_dict)
```

I get the following error at `image_dict[identifier] = Image2DModel().parse(data=page.asarray())`:

```
np.arange(data.shape[2], dtype=np.float64) * scale["x"] + translation["x"],
IndexError: tuple index out of range
```

The error is resolved if I change that line to:

```
image_dict[identifier] = Image2DModel().parse(data=np.array(Image.fromarray(page.asarray()).convert('RGB')))
```

suggesting that the array needs to be in RGB dimensions to pass the validation step for the 2D image model.

Attached is a zip of the file being used.

[multi_channel_image.zip](https://github.com/scverse/spatialdata/files/11908253/multi_channel_image.zip)

**Comment by LucaMarconato** [comment]
Thanks for the full code. The parser expects a cyx image by design, but you can make the code working by expanding the shape of the array, i.e. by passing this to the parser `np.expand_dims(page.asarray(), axis=0)`, no need to convert to RGB. I will now make the documentation clearer regarding this point, thanks for reporting.

**Comment by LucaMarconato** [comment]
Fixed the docstring in this commit: https://github.com/scverse/spatialdata/commit/4e554789aa9ff534fe3d70c784c6fda9bd4ca06e (pushed directly to main since it's a small change).
