### ISSUE TITLE
get_extent switches x and y

### ISSUE THREAD

**Issue by Sonja-Stockhaus** [scverse/spatialdata#335]
Hey @timtreis , @LucaMarconato ,

So in the branch feature/get_extent there is the new `get_extent` function which should be outsourced from spatialdata-plot.
I just compared it to the `_get_extent` function from spatialdata-plot and it looks like both compute the same numbers but the spatialdata output has the x and y coordinates switched which seems to be a bug. I added code to hopefully reproduce the issue.

Would be cool if you could have a look at it :)

```python
import spatialdata as sd
import spatialdata_plot

# This example doesn't really work with blobs (bc it has identical x and y extents), so I used the example data from https://s3.embl.de/spatialdata/spatialdata-sandbox/visium_associated_xenium_io.zip
visium_sdata = sd.read_zarr("visium_associated_xenium_io.zarr")

print("Old function (from spatialdata-plot):")
print(spatialdata_plot.pl.utils._get_extent(visium_sdata))
# output format is [xmin, xmax, ymin, ymax], so for "global" I get xmax = 19505
```
![image](https://github.com/scverse/spatialdata/assets/12818242/aad30d7b-7211-4113-a628-18d0971c601b)
```
print("New function (from spatialdata):")
print(sd._core.data_extent.get_extent(visium_sdata, coordinate_system="global"))
# This would imply ymax = 19505
```
![image](https://github.com/scverse/spatialdata/assets/12818242/52ad8b77-d702-49ff-b99b-8b7830736e40)
```
print("Ground truth:")
print(visium_sdata.images)
# (c: 3, y: 21571, x: 19505) would mean the spatialdata output is incorrect because x and y are swapped
``` 
![image](https://github.com/scverse/spatialdata/assets/12818242/8471ca69-a61e-48f0-9e44-a7c680cf1875)

**Comment by LucaMarconato** [comment]
Great catch Sonja, thanks for reporting!
