### ISSUE TITLE
Aggregation tutorial reversed section titles

### ISSUE THREAD

**Issue by ckmah** [scverse/spatialdata#337]
Hello, I believe in the current version of the "shapes by shapes" aggregation tutorial the headings for "Case: value_key referring to obs columns" and "Case: value_key referring to GeoDataFrame columns" are swapped. Just wanted to note this here!

https://spatialdata.scverse.org/en/latest/tutorials/notebooks/notebooks/examples/aggregation.html#case-value-key-referring-to-obs-columns

**Comment by LucaMarconato** [comment]
Hi, you are right, thanks for pointing this out, I added this to my todo list of fixes.
