### ISSUE TITLE
Rows annotating multiple regions

### ISSUE THREAD

**Issue by LucaMarconato** [scverse/spatialdata#34]
In the [`nanostring_cosmx` dataset](https://github.com/giovp/spatialdata-sandbox/tree/main/nanostring_cosmx) each row of the annotation matrix is associated to two regions, since each set of cells is saved both as a `Labels` and as a `Points` (with variable radius for the cells).

With the current specification each row of the table can annotate only one regions, I think we should support the above case, we have to explore how.

**Comment by ivirshup** [comment]
So they have two representations for the same regions? How common is that?

I think I'd be fine with making the metadata basically act as default arguments, then letting people specify they want to use a different region set with arguments.

**Comment by LucaMarconato** [comment]
It actually will be very common when building graphs on top of labels, since you would have points (with the graph in `obsp`) for the same regions, and you may want to plot sometimes the labels in the background and sometimes the points. 

Possible workaround following your suggestion: if the column corresponding to `regions_key`(the one that for each row of the annotation matrix has a reference to a Regions object) is a numerical index instead of the full path, then the user (or our methods) could quickly switch the target regions by simply modifying the values of `regions`.

**Comment by LucaMarconato** [comment]
I proposed a solution here: https://github.com/ome/ngff/pull/64#issuecomment-1414325090

**Comment by LucaMarconato** [comment]
Related https://github.com/scverse/spatialdata/issues/99

**Comment by LucaMarconato** [comment]
This is solved by the new multi-table PR https://github.com/scverse/spatialdata/pull/455. We don't allow to annotate multiple elements, but we have an helper function to quickly choose what the table is annotating:
```python
full_sdata.set_table_annotates_spatialelement("table", "poly")
```
