### ISSUE TITLE
Update Multiscales and new transform specs when ome-ngff 0.5 lands

### ISSUE THREAD

**Issue by LucaMarconato** [scverse/spatialdata#35]
At the moment multiscale information is not written with the new transform specs since `ome-zarr-py` expects the old specification.

**Comment by kevinyamauchi** [comment]
The new transform specs still have not landed. We can revisit this when OME-NGFF 0.5 is approved.

**Comment by LucaMarconato** [comment]
Marking as stale, we can reopen when https://github.com/ome/ngff/pull/138 is merged.
