### ISSUE TITLE
TableModel accepts tables incompatible with zarr backend

### ISSUE THREAD

**Issue by MobiTobi** [scverse/spatialdata#351]
## unexpected behaviour

Anndata objects can be created using sparse matrices from `scipy.sparse`.
`TableModel.parse` and `TableModel.validate` accept these anndata objects silently.
Trying to save the spatial objects results in:
``` anndata._io.specs.registry.IORegistryError: No method registered for writing <class 'scipy.sparse._arrays.csr_array'> into <class 'zarr.hierarchy.Group'>```

An object parsed and validated using spatialdata should be compatible with spatialdata.

## expected behaviour

Slight preference for the first option
- `TableModel.parse` casts the sparse matrix to dense and warns the user of the implicit conversion
- `TableModel.parse` rejects the AnnData object

**Comment by LucaMarconato** [comment]
Thanks for reporting! Very weird problem, it should not happen. @giovp is going to work on the models soon, can you please also have a look at this?

**Comment by giovp** [comment]
sorry taking a look just now, this should definitely work as anndata support serializing sparse matrices to zarr. Would you be able to provide a reprex? thanks!
