### ISSUE TITLE
Napari Saving Shapes or Points Layers to SpatialData

### ISSUE THREAD

**Issue by benedekp** [scverse/spatialdata#381]
Hi,

I started to explore the methods available with SpatialData as I find it very useful. However I ran into some issues when trying to follow the "Use landmark annotations to align multiple -omics layers" tutorial. After opening the layers I want to align I added a Points layer, but when trying to save to the SpatialData with "SHift +E" nothing happens. I tried adding a different layer like Shapes, then it recognizes the key command, however I get the following Error:
```
File "/home/pestib/scratch/conda/envs/spatialdata_env/lib/python3.9/site-packages/napari_spatialdata/_view.py", line 300, in _save_shapes
    points_mask: NDArrayA = _points_inside_triangles(self.model.coordinates[:, 1:], triangles)
TypeError: 'NoneType' object is not subscriptable
```

**Comment by LucaMarconato** [comment]
Hi @benedekp happy to hear that you find it useful 😊 

We had to refactor the saving feature, which now is re-implemented in https://github.com/scverse/napari-spatialdata/pull/168 and will be merged to main this week, but you can already use it. The new implementation is more stable, has more tests and deals better with the case in which multiple `SpatialData` objects are present, letting the user choose where to save the annotations. Unfortunately this new implementation took longer than anticipated, sorry about this.
