### ISSUE TITLE
Replace SpatialImage and MultiscaleSpatialImage with DataArray and DataTree

### ISSUE THREAD

**Issue by LucaMarconato** [scverse/spatialdata#395]
The new releases of `spatial_image` and `multiscale_spatial_image` use these the base classes `DataArray` and `DataTree`. We need to:
- [ ] add support for these classes
- [ ] remove the version pin from the dependencies in `pyproject.toml`

Note. This modification will introduce a breaking change. I propose to develop this feature in a parallel branch that we release together with the rest of IO refactoring. CC @giovp @melonora @kevinyamauchi

**Comment by melonora** [comment]
Just regarding the last point, we need to pin the version to 1.1.0 because of the update regarding rgb.
