### ISSUE TITLE
Rename `MultiscaleSpatialImage` coords inplace

### ISSUE THREAD

**Issue by quentinblampey** [scverse/spatialdata#402]
Hello,

I'm trying to rename the coordinate names of my channels (`"c"`).

With a `MultiscaleSpatialImage`, this would be simply `new_image = image.assign_coords(c=[...])`, which works fine but isn't an inplace operation. Therefore I have to make the update `sdata[image_key] = new_image`, but I can't since `new_image` is now a `DataTree` and not a `MultiscaleSpatialImage`...

I could also simply change the class of my datatree before updating the spatialdata object, i.e.:
```
new_image.__class__ = MultiscaleSpatialImage
sdata[image_key] = new_image
```

But well, this is quite ugly and it doesn't work when the data is backed (`ValueError: Cannot add the image to the SpatialData object because it would overwrite an element that it isusing for backing. See more here: https://github.com/scverse/spatialdata/pull/138`)

Maybe I missed something much easier?
Thanks!

**Comment by LucaMarconato** [comment]
Hi Quentin, converting a `DataTree` object to a `MultiscaleSpatialImage` object can be done with the helper function https://github.com/scverse/spatialdata/blob/6bb361b8eb7fcbac1312c2fb89e07a123decaea8/src/spatialdata/_utils.py#L155.

This conversion will not be needed anymore when we will transition to the latest `spatial_image` and `multiscale_spatial_image` packages as explained in this issue https://github.com/scverse/spatialdata/issues/395.

Finally, we are improving the support for the incremental update of `SpatialData` object; there is still work to do, but an initial PR has been merged here https://github.com/scverse/spatialdata/pull/329.

**Comment by quentinblampey** [comment]
Thanks, I didn't know about `multiscale_spatial_image_from_data_tree`!
It is a great temporary solution, and I will wait for the release that uses the new versions of `spatial_image` and `multiscale_spatial_image ` (indeed, I also think that it will be much easier to work only on `DataTree` objects)
