### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by goanpeca** [scverse/spatialdata#403]
Hello team!

While working on https://github.com/conda-forge/spatialdata-feedstock/pull/1

We noticed that the following packages are imported directly in code but not declared as dependencies in the `pyproject.toml`. Even if a dependency is available indirectly via the installation of another package, if it is imported in source, it should be added as an explicit dependency.

- click
- dask
- pandas
- scikit-image
- scipy
- xarray-datatree

Also, sorting dependencies alphabetically inside the toml file, helps with updating dependencies in the future ;) 

Could you please update this for the next release?

Thanks, and cheers 🚀

**Comment by LucaMarconato** [comment]
Hi, thank you for reporting this. I will incorporate this for the next release 😊 We need to update some notebooks before the release, I think it will be ready in 1-2 weeks.

Btw, talking about conda, we have been asked if the package could be put in bioconda here https://github.com/scverse/spatialdata/issues/252, what are your opinions on this?

**Comment by LucaMarconato** [comment]
Thanks again, I updated the dependencies as suggested.
