### ISSUE TITLE
Lazy loading of points and spatial index

### ISSUE THREAD

**Issue by kevinyamauchi** [scverse/spatialdata#41]
@LucaMarconato has observed that load lots (1E6) points is slow. Thus, we should discuss lazy loading and using some sort of spatial index for query.

A few points:
- we need to define the access patterns we want to support and prioritize which should be fastest
- we need to determine if delayed loading is sufficient or if we need a spatial index
- we should separately consider analysis and rendering cases
- we need to decide if spatial index should be able to be saved/loaded

**Comment by LucaMarconato** [comment]
Lazy loading is now supported. Spatial index could be achieved using `Dask` `GeoDataFrame` for points. We are still considering this.

**Comment by LucaMarconato** [comment]
- [ ] after this is implemented we should explain how to use it in the docs.

**Comment by melonora** [comment]
Since #359 contains the information of the remainder of the work I will close this issue.
