### ISSUE TITLE
`contains_element` returns False if element is contained more than once

### ISSUE THREAD

**Issue by aeisenbarth** [scverse/spatialdata#425]
SpatialData allows an element to be contained more than once with different names. When checking whether it is contained, the result is unexpectedly False although the element is contained.

## Example

```python
from spatialdata import SpatialData
from spatialdata.models import Image2DModel
import numpy as np
img = Image2DModel.parse(np.arange(4).reshape((1, 2, 2)), dims=("c", "y", "x"))
sdata = SpatialData(images={"img1": img, "img2": img})
assert sdata.contains_element(img)
```

## Cause

`_locate_spatial_element` raises a ValueError if the element is not found and another ValueError if the element is found more than once. `contains_element` catches both and returns False, but it should catch the second case separately and return True.

It's maybe worth to consider whether to disallow the same element under different keys (how would that be represented on disk?), because it is a very special edge case that breaks many other code places of spatialdata (e.g. `_write_transformations_to_disk`) and would need to be completely covered by test cases (if it has already any).

Instead of having `contains_element` inspect the AssertionError string from `locate_spatial_element` to distinguish the two ValueErrors, we could either have ValueError subclasses, or a private helper method that returns the counts of found elements (0, 1, 2…) instead of raising exceptions.

**Comment by melonora** [comment]
I agree, I don't see a benefit of it either, just added complexity.

**Comment by giovp** [comment]
mmh I really don't know though, I think this should be checked before and not with the check in #427 . Either a SpatialData can be instantiated with copies of elements or it can't. AnnData allows it for instance, so not sure why we shouldn't. I think on the contrary there is additional complexity on checking for the same element being present, as it should be done for sure at instantiation/IO and maybe in other parts (e.g. in subset ?).

**Comment by LucaMarconato** [comment]
I agree, it should be checked before, I'd say at instantiation (constructor and`init_from_elements`) and when the user uses the syntaxes `sdata.images['xxx'] = xxx`. I'd still keep it also in `locate_element()` as a double check for safety, to make sure that the result is not ambiguous.

**Comment by melonora** [comment]
@giovp What is the reason in AnnData for allowing it? Coming back to think about this, I would not see a use case personally right away. On the other hand what would be the problem (other than what @aeisenbarth reported currently) if the name of the element is different?

**Comment by giovp** [comment]
I don't think checking that the element value is unique is something we should enforce, I don't see a use case but also I think it creates quite some constraints. Why not just returning a list of str in `locate_element` in #427 , what's the issue?

**Comment by melonora** [comment]
yes, I agree. It is what I tried to point at as the only problem currently is that `False` gets returned. If a user has added one element twice with different names it is an intention of the user. We can just return the corresponding keys.

**Comment by LucaMarconato** [comment]
Ok, I have changed `locate_element()` and to return an optional list of strings.

**Comment by aeisenbarth** [comment]
Semantically, an empty list of strings equally expresses "not found", just like None. But it is a simpler type, and one needs less code to work with the return value.

Using current implementation:
```python
locations: Union[list[str], None] = locate_element(...)
# Use case 1
if locations is not None:
    first_location = locations[0] # assuming list is never returned empty
# Use case 2
if locations is not None:
    for location in locations:
        ...
```
Using empty list:
```python
locations: list[str] = locate_element(...)
# Use case 1
if locations:
    first_location = locations[0] # assuming list is never returned empty
# Use case 2
for location in locations:
    ...
```

**Comment by LucaMarconato** [comment]
Very true, I was still focused on the older approach, gonna make a quick patch now.
