### ISSUE TITLE
NotImplementedError: Multiscale images are not implemented yet?

### ISSUE THREAD

**Issue by duongvtt96** [scverse/spatialdata#428]
Hi, I tried to run the [densenet.ipynb notebook](https://spatialdata.scverse.org/en/latest/tutorials/notebooks/notebooks/examples/densenet.html), but faced an error when creating `ImageTilesDataset`: NotImplementedError: Multiscale images are not implemented yet.
The original code is 
`dataset = ImageTilesDataset(
    sdata=merged,
    regions_to_images={"cell_circles": "CytAssist_FFPE_Human_Breast_Cancer_full_image"},
    tile_dim_in_units=3 * xenium_circles_diameter,
    tile_dim_in_pixels=32,
    target_coordinate_system="aligned",
    transform=my_transform,
)`
and was modified to:
`dataset = ImageTilesDataset(
    sdata=merged,
    regions_to_images={"cell_circles": "CytAssist_FFPE_Human_Breast_Cancer_full_image"},
    tile_dim_in_units=3 * xenium_circles_diameter,
    #tile_dim_in_pixels=32,
    #target_coordinate_system="aligned",
    regions_to_coordinate_systems={"cell_circles": "aligned"},
    transform=my_transform,
)`
with spatialdata version=0.0.16.dev24+ga5336d8 installed from GitHub. 

Do you have any suggestions for this issue? Thank you.

**Comment by LucaMarconato** [comment]
Thanks for reporting, I will close this issue and continue the discussion here: https://github.com/scverse/spatialdata/issues/428.
