### ISSUE TITLE
Inconsistency in parameter `filter_by_coordinate_system`

### ISSUE THREAD

**Issue by melonora** [scverse/spatialdata#433]
When refactoring some code for #410 I noticed that there is an inconsistency in the parameters. In [`filter_by_coordinate_system`](https://github.com/scverse/spatialdata/blob/98c5cbce7b4e00d9c4c2ce208539ab1d75f406df/src/spatialdata/_core/spatialdata.py#L448) we pass on `element_paths_in_coordinate_system` to `_filter_table_by_coordinate_system`. However, looking at this function the argument here refers to `coordinate_system`.

**Comment by LucaMarconato** [comment]
Yeah it seems to be wrong (even if I never noticed any side effect). We can fix it and add a test.
