### ISSUE TITLE
`xarray-spatial` depends on `numpy<=1.23.4`, `scanpy` does not support `numpy==1.23`

### ISSUE THREAD

**Issue by LucaMarconato** [scverse/spatialdata#440]
From @quentinblampey.

Today, the version 1.9.7 of scanpy was released, but their plots are incompatible with numpy 1.23 (see here https://github.com/scverse/scanpy/issues/2830) but xarray-spatial depends on numpy<=1.23

**Comment by flying-sheep** [comment]
Fixed in scanpy 1.9.8
