### ISSUE TITLE
Ability to add Table(s) to Coordinate Systems

### ISSUE THREAD

**Issue by srivarra** [scverse/spatialdata#443]
Thanks for working on multi table support! I've been using the recent [_multi_table_ branch](https://github.com/scverse/spatialdata/tree/multi_table) and it's been working pretty well so far. One nice feature would be the ability to add a table to coordinate system with a transformation.

For my particular use case, the purpose of this would be to group all related components of a particular field of view together for easy iteration / accession.

For example, being able to do the following:
```python
import spatialdata as sd

sd.transformations.set_transformation(
		element=sdata.tables["fov0_whole_cell_table"],
		transformation=sd.transformations.Identity(),
		to_coordinate_system="fov0"
)
```

Where the coordinate system `"fov0"` now would have:
```
▸ 'fov0', with elements:
        fov0 (Images), fov0_nuclear (Labels), fov0_whole_cell (Labels), fov0_whole_cell_table (Tables)
```

I think the `SpatialElement` union type would need to be extended to support `AnnData` tables as well, amongst other changes. 

Perhaps `TableModel.parse` method could have the coordinate transformation arguments as well.

```python
class TableModel:
	...
		@classmethod
		def parse(
			  cls,
			  adata: AnnData,
			  region: str | list[str] | None = None,
			  region_key: str | None = None,
			  instance_key: str | None = None,
			  # New parameter
			  transformations: MappingToCoordinateSystem_t | None = None,
```

And the usage of parse could be:

```python
sd.models.TableModel.parse(
		adata=fov0_adata,
		region="fov0_whole_cell",
		region_key="region",
		instance_key="instance",
		transformations={"fov0": sd.transformations.Identity()
}
```

Is this particular feature within scope for how tables should operate in SpatialData?

**Comment by srivarra** [comment]
@LucaMarconato 

> Regarding allowing tables to have an associated coordinate system, this would clash with the case in which a table is annotating multiple elements, each belonging to a different coordinate system.

Yup, makes perfect sense to me.

I think the first approach sounds good for now, but the arbitrary hierarchy NGFF sounds _perfect_!

Thank you!

**Comment by LucaMarconato** [comment]
Happy to hear this and looking forward to enable nested hierarchies! 😊 Closing this issue now as the progress will be tracked in #398.

**Comment by LucaMarconato** [comment]
> The function was not in the docs, I will update this with a PR I am currently working on.

Actually it was already in the docs but a bit hidden, since it's a method of the `SpatialData` class. We can make it more discoverable, tracking this in https://github.com/scverse/spatialdata/issues/225.
