### ISSUE TITLE
add_table() method would be consistent w. other add_[attribute]()

### ISSUE THREAD

**Issue by MichielVerCruysse** [scverse/spatialdata#451]
Adding a table as follows
sdata.table = myTable
is inconsistent with the method for adding images, labels, points and shapes. I feel like an add_table method would be clearer.

**Comment by LucaMarconato** [comment]
Thanks @MichielVerCruysse for reporting this. We actually fixed this inconsistency but we haven't made a release yet. It will probably take a few more weeks until we cut one.

We took another approach: in https://github.com/scverse/spatialdata/pull/329 we remove the `add_image()`, `add_labels()`, ... methods and in the branch https://github.com/scverse/spatialdata/tree/multi_table we added support for multiple tables. 

If you want you can already use these functions by installing the library from `main` or from the `multi_table` branch.
