### ISSUE TITLE
Using xarray to make transformations less ambiguous

### ISSUE THREAD

**Issue by LucaMarconato** [scverse/spatialdata#47]
Cost/benefit analysis of using `xarray` to annotate the dimensions of vectors (see code examples below).
Pro:
- would make transformations less ambiguous
- possibility to apply transformations to points of any shapes, for instance (n, 2) and (2, n).

Cons:
- extra verbosity for the use

Current approach: initially I am using `numpy` arrays for the vectors describing points and performing a shape check (e.g. 2D translations can't be applied to a set of points stored as a `numpy` array of shape `(2, n)`, but only with a shape `(n, 2)` (excluding edge cases like n=2).
Later we can discuss the preferred approach.

Code examples from @ivirshup of using `xarray.DataArray` to annotate the dimensions of vectors.
```
import xarray as xr

da = xr.DataArray([1,2,3], coords={"dim": ["x", "y", "z"]})

da.sel({"dim": "x"})
<xarray.DataArray ()>
array(1)
Coordinates:
    dim     <U1 'x'
```

```
import xarray as xr, numpy as np

N_POINTS = 10
points = xr.DataArray(
    np.random.random((N_POINTS, 3)),
    coords={
        "points": range(N_POINTS),
        "dim": ["x", "y", "z"],
    },
)
points
<xarray.DataArray (points: 10, dim: 3)>
array([[0.97379558, 0.29238395, 0.37392129],
       [0.62459118, 0.13214354, 0.0514482 ],
       [0.41742495, 0.59828447, 0.79762354],
       [0.87583248, 0.71631053, 0.30032732],
       [0.93012066, 0.73074886, 0.46370001],
       [0.74505332, 0.84503157, 0.52606046],
       [0.85789939, 0.44050558, 0.23522551],
       [0.35954281, 0.11675383, 0.23321456],
       [0.99866969, 0.83124205, 0.55161158],
       [0.25951685, 0.09205387, 0.00736066]])
Coordinates:
  * points   (points) int64 0 1 2 3 4 5 6 7 8 9
  * dim      (dim) <U1 'x' 'y' 'z'
```

```
translation = xr.DataArray([0, 1, 0], coords={"dim": ["x", "y", "z"]})
points + translation
```

**Comment by ivirshup** [comment]
How could this interact with shapely/ geopandas? It looks like [geopandas](https://geopandas.org/en/stable/docs/reference/api/geopandas.GeoSeries.x.html) and [shapely](https://shapely.readthedocs.io/en/latest/reference/shapely.Point.html) effectively hardcode x, y, z

**Comment by LucaMarconato** [comment]
Good catch. I'll think about it. I think that https://github.com/scverse/spatialdata/issues/39) is also related (more details in the linked issue).

**Comment by LucaMarconato** [comment]
The transformations are now using this approach internally to apply the transformations.
