### ISSUE TITLE
Improve docs

### ISSUE THREAD

**Issue by LucaMarconato** [scverse/spatialdata#477]
Would be nice to improve a bit the docs before the next release. Here is a list of parts that we could improve.
- [x] notebook on data models ("How to put my data in the SpatialData format")
In particualar:
- [x] focus on the levels on `MultiscaleSpatialImage` and its relationship with `SpatialImage` https://github.com/scverse/spatialdata/issues/355
- [x] how to use channel names in raster data
- [x] tutorial on multiple tables
- [x] tutorial on Xenium data
- [x] tutorial on Visium HD data
- [x] link the notebooks from @ quentinblampey in the docs

Minor improvements referenced in other issues (look for the unticked checkboxes):
- [x] https://github.com/scverse/spatialdata/issues/469
- [x] https://github.com/scverse/spatialdata-io/issues/117

**Comment by LucaMarconato** [comment]
Thank you @MobiTobi for the feedback. Regarding the usage of the spatial index I would suggest to keep track of it here: https://github.com/scverse/spatialdata/issues/41; 
- [ ] but after that we should indeed explain this in the documentation.

**Comment by melonora** [comment]
Copied from multi table tests:

#     The following use cases needs to be put in the tutorial notebook, let's keep the comment here until we have the
#     notebook ready.
#     # these use cases could be the preferred one for the users; we need to choose one/two preferred ones (either this,
#     either helper function, ...)
#     # use cases
#     # use case example 1
#     # sorting the shapes to match the order of the table
#     sdata["visium0"][sdata.table.obs["__instance_id__"]]
#     assert ...
#     # use case example 2
#     # sorting the table to match the order of the shapes
#     sdata.table.obs.set_index(keys=["__instance_id__"])
#     sdata.table.obs[sdata["visium0"]]
#     assert ...
#
#     We can postpone the implemntation of this test when the functions "match_table_to_element" etc. are ready.
# def test_partial_match():
#     # the function spatialdata._core.query.relational_query.match_table_to_element(no s) needs to be modified (will be
#     # simpler), we need also a function match_element_to_table. Maybe we can have just one function doing both the
#     things,
#     # called match_table_and_elements test that tables and elements do not need to have the same indices
#     pass
#     # the test would check that we cna call SpatiaLData() on such combinations of mismatching elements and that the
#     # match_table_to_element-like functions return the correct subset of the data

**Comment by LucaMarconato** [comment]
- [ ] Comment on data models usage discussed here: https://github.com/scverse/spatialdata/issues/499

**Comment by LucaMarconato** [comment]
- [ ] fix hyperlink: https://github.com/scverse/spatialdata/issues/502

**Comment by LucaMarconato** [comment]
- [ ] Discussion around `shapely` objects with `z` in the models notebook, as outline here: https://github.com/scverse/spatialdata-plot/issues/230.

**Comment by melonora** [comment]
@LucaMarconato can this one be closed now?
