### ISSUE TITLE
Adjust for dask expressions update

### ISSUE THREAD

**Issue by melonora** [scverse/spatialdata#482]
With `dask-exprs` landed, we need to adjust the code base for compatibility. Until we are compatible the version of dask used is constrained to a specific version.

**Comment by ivirshup** [comment]
FWIW they ended up revert a bit that was giving us problems in scanpy and anndata https://github.com/dask/dask-expr/pull/974

**Comment by giovp** [comment]
closed in #481

**Comment by LucaMarconato** [comment]
Correction, closed here: https://github.com/scverse/spatialdata/pull/570/files
