### ISSUE TITLE
Readthedocs link points to another project

### ISSUE THREAD

**Issue by berl** [scverse/spatialdata#49]
I'm guessing people here are aware of this, but I didn't see another issue here and figured it would be good to have it on paper:

the current link in [readme.md](https://github.com/scverse/spatialdata/blob/bf1a95637da2f2e997314acdc00794fab547ff1a/README.md) points to `https://spatialdata.readthedocs.io/latest/` which 404's and if you remove the `/latest` you end up at the `readthedocs` page for another (identically named) project at [https://spatialdata.readthedocs.io/en/latest/](https://spatialdata.readthedocs.io/en/latest/)

**Comment by kevinyamauchi** [comment]
Hey @berl ! It's great to see you here :). Thanks for the heads up. We haven't really set up the docs yet, so we should probably remove the docs link for now - I think it just came with the cookiecutter when we setup the repo 😬
