### ISSUE TITLE
Order of tutorial notebooks

### ISSUE THREAD

**Issue by Zethson** [scverse/spatialdata#533]
Hey awesome people,

looking at https://spatialdata.scverse.org/en/latest/tutorials/notebooks/notebooks.html I would suggest to reorder the tutorials so that part I and part II are the first notebooks that people see and click at.

**Comment by LucaMarconato** [comment]
Hi 😁 Thanks for checking the docs. I actually wanted to do this but then after making the notebooks I realized that they were quite technical, so I moved them to the end. What do you think about the notebooks? Too technical or fine?

**Comment by Zethson** [comment]
I do think that they are somewhat technical but I think that the very first notebook should be an introduction to the structure of spatial data itself. If you deem them too technical and don't find a way to resolve this, you could consider splitting them into a `a users guide to spatialdata` and a `Technical background of spatialdata` type of tutorial.

**Comment by LucaMarconato** [comment]
I thought about this and moved the notebooks back to the first position; if it turns out that the notebooks are too technical after user feedback we may split them instead.
