### ISSUE TITLE
Typing-related bug with xarray_dataclasses when debugging

### ISSUE THREAD

**Issue by LucaMarconato** [scverse/spatialdata#54]
The following line (I have created a Python file with just this line)
```
from xarray_dataclasses.dataarray import AsDataArray
```
which is invoked by `multiscale-spatial-image`, gives me an error (see screenshot) when debugging (I am using PyCharm). No exception is raised when running the code normally (again I am using PyCharm).

I am using `Python 3.9.13` and I have configured the env with `pip install -e .`.

@kevinyamauchi you are using a similar setup and install config as mine, can you reproduce the bug? 
<img width="894" alt="Screen Shot 2022-11-29 at 22 04 43" src="https://user-images.githubusercontent.com/2664412/204647400-0a964140-ba1f-4e0e-8d08-ed1e4c13bd04.png">

**Comment by LucaMarconato** [comment]
I can't isolate the bug.
I created a clean conda env with `conda create -n bug python=3.9.13`, used `pip install xarray-dataclasses` and then created a PyCharm project with one file and the line above. Run and debug both work.

**Comment by LucaMarconato** [comment]
Reinstalling Python 3.9 didn't help, but using Python 3.10 made the issue disappear.

**Comment by kevinyamauchi** [comment]
Closing because I no longer see this bug.  @LucaMarconato , please feel free to re-open if you still see this bug.
