### ISSUE TITLE
Overlay custom shape onto cell boundaries from Xenium

### ISSUE THREAD

**Issue by EST09** [scverse/spatialdata#547]
Hi,

This may be a question for SOPA but I thought it was also worth asking here as well please.

I have custom polygon segmentation for a particular cell type derived from H&E. I've added this as a shape to my spatialdata object in the same coordinate system as cell boundaries (the default Xenium segmentation). I'd love to overlay this custom segmentation onto the default Xenium cell segmentation (cell boundaries) so that any cells/transcripts in the default under the custom segmentation get merged into the custom segmentation but the other cells from the default are kept.

In an ideal world I'd end up a new segmentation which is mostly cell_boundaries with the custom segmentation replacing cells it overlaid. 

I've been struggling a bit with how to achieve this and was wondering if the functionalities already present in spatialdata/SOPA. I've been looking at https://spatialdata.scverse.org/en/latest/tutorials/notebooks/notebooks/examples/tables.html, a use case for table, but haven't managed to implement it yet.  

Best wishes,
Emily

**Comment by LucaMarconato** [comment]
Thanks for the appreciated feedback, and great to hear that now the feature is implemented in SOPA! 🎉 I'll close the issue.
