### ISSUE TITLE
Can't save  transformation result

### ISSUE THREAD

**Issue by Ithinky** [scverse/spatialdata#558]
Hi,
Thanks for your great work in Spatial omics filed!
I used SpatialData to integrate two images and following the tutorial "Use landmark annotations to align multiple -omics layers". Everything went well, but when I wanted to save the result  by save_transformations( ) , the information returned like this 
![image](https://github.com/scverse/spatialdata/assets/92069388/53e53a5b-9a3c-4568-9062-7de28009cb9a)
. And the recommend function write_transformations( ) can't be used.
My SpatialData objects are here:
![image](https://github.com/scverse/spatialdata/assets/92069388/acb32f41-441b-477a-95a8-0fe7838f571a)
![image](https://github.com/scverse/spatialdata/assets/92069388/410560ad-ae67-477d-8a5f-9dc16c61755a)

By the way, after alignment, where can I get the  alignment relationship between pixel spots in two image, like spot1 in image1 is aligned to spot3 in image2?

I would appreciate it if you could help me!

**Comment by Ithinky** [comment]
Thanks for your fast reply! I will try it.

**Comment by Ithinky** [comment]
How can I call write_element( ), I can't import it from spatialdata_io or spatialdata. Thank you again!

**Comment by melonora** [comment]
it is not an import. If you have a spatialdata object you can call it as a method of the spatialdata object directly, no import required. So for example my spatialdata object is called sdata and I have an element called `registration_landmarks` that I just added in memory to the object, the way to write it do disk is:

```
sdata.write_element("registration_landmarks")
```
Let us know if you have any issues!

**Comment by melonora** [comment]
btw just so you know the PR as @LucaMarconato stated is not merged yet, so if you would like to try you have to either clone the repo, checkout the PR using the github cli and perform an editable install, or have a bit of patience:)

**Comment by melonora** [comment]
@Ithinky getting back to you, we are cutting the release that includes the method in the following days. I will close this issue now.
