### ISSUE TITLE
How to create a spatialdata object from a VisiumHD dataset preprocessed by spaceranger?

### ISSUE THREAD

**Issue by OMIC-coding** [scverse/spatialdata#563]
Using the spatialdata_io.visium_hd function to load the output of spaceranger for a visiumHD dataset can only generate an object with no shapes or tables, which cannot be directly used to plot the spatial distribution of a given gene expression. The tutorial for VisiumHD analsyis pipeline only showed the steps starting from .zarr file, but we don't know how to construct such type of data from spatialdata_io.visium_hd sdata object.
The outputs of sdata.pl.render_images for sdata loaded by spatialdata_io.visium_hd function are as follows:
SpatialData object with:
└── Images
      ├── 'WTF_1_hires_image': SpatialImage[cyx] (3, 5220, 6000)
      └── 'WTF_1_lowres_image': SpatialImage[cyx] (3, 522, 600)
with coordinate systems:
▸ 'downscaled_hires', with elements:
        WTF_1_hires_image (Images)
▸ 'downscaled_lowres', with elements:
        WTF_1_lowres_image (Images)

**Comment by LucaMarconato** [comment]
Hi, it sounds like that there is a naming difference between the Visium HD data as downloaded from the 10x website and the ones that you have. 

Here you can find the script that we used to download the data (which lists the data files that are expected) and the script use to convert the raw data to Zarr.

To fix your problem renaming the files should be enough. Please let me know if it works for you.
Also, in case you didn't rename the files obtained from spaceranger, could you please copy-paste here the list of filenames? In this way we can try to extend the readers to take into account also for them. Thanks.

**Comment by OMIC-coding** [comment]
No, I didn't rename the files obtained from spaceranger, my outputs are as follows:

![Uploading 截屏2024-05-25 14.56.41.png…]()

**Comment by OMIC-coding** [comment]
No, I didn't rename the files obtained from spaceranger, my outputs are as follows:
drwxrwxr-x 4 bailab bailab         302 May 10 16:28 .
drwxrwxr-x 4 bailab bailab        4096 May 10 16:28 ..
drwxrwxr-x 5 bailab bailab          82 May 10 16:29 binned_outputs
-rw-rw-r-- 1 bailab bailab   780439403 May 10 16:28 cloupe_008um.cloupe
-rw-rw-r-- 1 bailab bailab   443339057 May 10 16:27 feature_slice.h5
-rw-rw-r-- 1 bailab bailab        1712 May 10 16:27 metrics_summary.csv
-rw-rw-r-- 1 bailab bailab   788417828 May 10 16:27 molecule_info.h5
-rw-rw-r-- 1 bailab bailab 68890433320 May 10 16:51 possorted_genome_bam.bam
-rw-rw-r-- 1 bailab bailab     2640200 May 10 16:28 possorted_genome_bam.bam.bai
-rw-rw-r-- 1 bailab bailab     6134282 May 10 16:27 probe_set.csv
drwxrwxr-x 2 bailab bailab         217 May 10 16:28 spatial
-rw-rw-r-- 1 bailab bailab    18037026 May 10 16:27 web_summary.html

**Comment by LucaMarconato** [comment]
From the list that you gave, the reason why the object that you obtain is without the shapes information is because the folders `square_002um`, `square_008um` are missing.

I would suggest controlling if there is a setting in spaceranger that was toggled off and that led to the omission of these files.

**Comment by OMIC-coding** [comment]
But folders square_002um, square_008um, square_016um are in binned_outputs folder by default.
(By default, this directory has three subdirectories: square_002um, square_008um, and square_016um. Each directory contains filtered_feature_bc_matrix, raw_feature_bc_matrix, spatial, filtered_feature_bc_matrix.h5, and raw_feature_bc_matrix.h5. The analysis directory is only provided at 8 and 16 µm bin size. The cloupe.cloupe is only provided at 8 µm bin size. The raw_probe_bc_matrix.h5 is only provided at 2 µm resolution.)

**Comment by LucaMarconato** [comment]
It could be that the default output path changed with the latest version of spaceranger. I will match a patch, for the moment I suggest to try moving the square_002um, ... folders one folder up. You can also accomplish this using symlinks so that you don't have to modify the data structure. Please let me know if it solves your issue.

**Comment by LucaMarconato** [comment]
I added a fix here https://github.com/scverse/spatialdata-io/pull/149, please let me know if it solves your issue.

**Comment by OMIC-coding** [comment]
This problem did be solved by moving the square_002um one folder up. But I encounter another bug when plotting gene expression (InvalidIndexError: Reindexing only valid with uniquely valued Index objects). In addition, duplicated var names cannot be removed by var_names_make_unique function, because the it cannot recognize any object but a table format.

**Comment by LucaMarconato** [comment]
Great to hear that the issue with the bins got solved, I will merge the fix in `spatialdata-io`. Please report plotting-related bugs to https://github.com/scverse/spatialdata-plot/ as they are handled by other developers of the team.

The `napari-spatialdata` codebase is independent from `spatialdata-plot`, so meanwhile you can maybe use interactive plotting with

```python
from napari_spatialdata.import Interactive
Interactive(sdata)
```

Regarding this issue
> In addition, duplicated var names cannot be removed by var_names_make_unique function, because the it cannot recognize any object but a table format.

please report open another issue and attach a minimal reproducible example so we are able to debug it. We prioritize issues that have runnable code attaached.
