### ISSUE TITLE
Only `List[str]` for the `region` attribute

### ISSUE THREAD

**Issue by LucaMarconato** [scverse/spatialdata#57]
As pointed out by Will Moore here https://github.com/ome/ngff/pull/64/files#r1022811943, it would be cleaner if `regions` could only be a list, instead than either a single string or a string of list.

Let's see how the specification evolves and eventually update our code.

**Comment by melonora** [comment]
Closing this issue for now. Will open an issue, together with @LucaMarconato decided to drop region in uns alltogether.
