### ISSUE TITLE
Saving large files to .zarr

### ISSUE THREAD

**Issue by asom** [scverse/spatialdata#571]
Hi,

I am trying to save a big SpatialData object (sdata) containing Xenium and Codex data to .zarr file, using the follwoing command:

`sdata.write(***PATH***, overwrite=True)`

However, I do get the following error:

> 119 if max_buffer_size is not None and arr.nbytes > max_buffer_size:
> 120     msg = "Codec does not support buffers of > {} bytes".format(max_buffer_size)
>  -->` 121     raise ValueError(msg)
> 123 return arr
> 
>  ValueError:` Codec does not support buffers of > 2147483647 bytes

Is there any way I could save this file? 

In general, I am saving it in order to load it afterwards to napari following this tutorial:

> https://spatialdata.scverse.org/projects/napari/en/latest/notebooks/spatialdata.html

Is there any other way I could circumvent writting?

**Comment by LucaMarconato** [comment]
Hi, the problem could be that the images/labels are not converted to multiscale images, or that the chunks for the images/labels are too large.

I would check this. To check the first you can see the output of `print(sdata)`, if images have just one resolution, they are single-scale images, if you get a list of resolutions, you have multiscale objects.

To check the second you can access `sdata['my_image'].chunks` and `list(sdata['my_multiscale_image']['scale0'].values)[0].chunks`.

**Comment by melonora** [comment]
Closing this issue for now but feel free to reopen if the issue persists.
