### ISSUE TITLE
Experiment with rasterization on Visium HD like

### ISSUE THREAD

**Issue by LucaMarconato** [scverse/spatialdata#572]
CC @quentinblampey 

For Visium HD data, a full rasterization of the vector spatial information is not possible because, considering resolution, number of genes, and sparsity, the rasterized object would explode in size (for the 2µm bins, it would lead to ~100GB, assuming 1 byte per pixel per gene).

A to solution this could be to rasterize channels of Visium HD data on-the-fly. This is also what probably is done with Loupe Browser, by fetching the data from `hd_slice.hdf5`, which contains a channel-wise sparse repreentation of the data.

Things to try and benchmark, to see **what's the good trade-off of speed and generalizability of the code** (we want the same approach to work also for Stere-seq data):

# baseline for the full data
- [x] Implement a baseline on-the-fly rasterization of single channels. 
	- [x] The annotation tables should be converted first to have `csc` representation. By default they are `csr`. 
	- *Skipped as we opted for passing the bins coordinates explicitly*. Also, the output shape of the rasterized object should be computed automatically as the number of "expected bins" of the data. This can be done by computing, for each axis, the minimum non-zero-like distance between pairs of points and then dividing the extend of the data by this number.

# baseline for crops
- *Skipped as the performance is very good so it's easier to rasterize and then crop.* Now call `.subset()` to keep only the points and then `bounding_box_query()`, this will create a lazy `SpatialData` object for the points in the crop. Now rasterize. 

# improved rasterization for the full data
- [x] *Note: we use this approach by default now, since calling `rasterize()` is significantly slower.* a way maybe to improve the rasterization speed is to avoid using `rasterize()` and instead to directly pre-allocate an array of zeros and then fill it in directly at the non-zero entries. 

# improved rasterization for the crops
- [x] I suspect that rasterizing a single crop will require mostly the same time as rasterizing the full data because of the bottleneck being the query operation. 
	- *Skipped as not needed, we can rasterize the full data and then crop.* We should try benchmarking against a simple reimplementation of the axis-aligned bounding box query for points, where we first construct a geopandas object for the points and then we compute a spatial index. 
	-  *Skipped as not needed, we can rasterize the full data and then crop.* The benchmark should be run against (say) 100 rasterization on subcrops, to see if there is a gain in amortized cost (which offsets the setup time of computing the spatial index).

**Comment by quentinblampey** [comment]
Corresponding PR: https://github.com/scverse/spatialdata/pull/578#issuecomment-2163142413
