### ISSUE TITLE
`set_table_annotates_spatialelement` doesn't return a valid table

### ISSUE THREAD

**Issue by giovp** [scverse/spatialdata#580]
https://github.com/scverse/spatialdata/blob/9e07583f13a70be0855c94ce54b18f133f5ab5b8/src/spatialdata/_core/spatialdata.py#L432

using this, it returns a table that is not valid. Specifically, it fails at write time due to region not being categorical. I believe because the table is never actually parsed somehow, but important to check where does this check fail

cc. @lotte-vandevreken @lopollar

**Comment by melonora** [comment]
@giovp do you remember what the actual problem is here? The method actually does not return a table at all. This only works on tables that are already in the SpatialData object and thus must have been validated previously

**Comment by giovp** [comment]
mmh I don't really remember, maybe @lotte-vandevreken does? It was something about wrong validation though. Feel free to close otherwise

**Comment by lotte-vandevreken** [comment]
After calling the set_tables_annotates_spatialelement, I got an error when I tried to save the sdata object to a new zarr storage:
ValueError: `table.obs[region_key]` must be of type `categorical`, not `<class 'pandas.core.series.Series'>`.

The error was resolved after doing this: sdata.table.obs['region']=sdata.table.obs['region'].astype('category')

**Comment by melonora** [comment]
Thanks @lotte-vandevreken, I will have another look in a bit and report back

**Comment by melonora** [comment]
Found the issue and with #610 it should be fixed.
