### ISSUE TITLE
currently assuming 2d

### ISSUE THREAD

**Issue by LucaMarconato** [scverse/spatialdata#6]
A spatialdata object should be either 2d or 3d (or more). Knowing the case is important, e.g. for creating a default identity transformation in the class `Transform`. 

For the moment I am assuming 2d data.

Later on we should implement a `.ndim` attribute that:
1. computes the ndim value
2. checks that the various building blocks are consistent to this

**Comment by kevinyamauchi** [comment]
I agree we should have an `ndim` attribute! Based on my understanding of our Heidelberg hackathon, it sounds like we will start assuming the data are 2D. Perhaps we can still have an `ndim` attribute that at least returns `2`.

In addition, eventually, I think we should support annotating the image axes in a standardized way to denote if it is a spatial axis as opposed to something else like color channel or time point.
