### ISSUE TITLE
numpy 2.0.0 support

### ISSUE THREAD

**Issue by LucaMarconato** [scverse/spatialdata#602]
We are postponing the support for numpy 2.0.0 because it seems that some dependent libraries (scikit-image, xarray-dataclasses) do not support it yet.

We can check this more in detail later on.

**Comment by giovp** [comment]
CI alread runs with numpy > 2.1 so i don't think this is an issue anymore

**Comment by ilan-gold** [comment]
Looks like this has popped up again https://github.com/scverse/integration-testing/actions/runs/11384930378/job/31673687459?pr=1

**Comment by LucaMarconato** [comment]
- [ ] Fix in case the logs disappear: using `np.ptp` instead of `my_arr.ptp`
