### ISSUE TITLE
set_table_annotates_spatialelement error

### ISSUE THREAD

**Issue by wangjiawen2013** [scverse/spatialdata#603]
Hi,
I'm following the tutorial of spatialdata (https://spatialdata.scverse.org/en/latest/tutorials/notebooks/notebooks/examples/tables.html) 
```
polygon_index = list(sdata.shapes["blobs_polygons"].index)
# We have to do a compute here as points are lazily loaded using dask.
point_index = list(sdata["blobs_points"].index.compute())

region_column = ["blobs_polygons"] * len(polygon_index) + ["blobs_points"] * len(point_index)
instance_id_column = polygon_index + point_index

import numpy as np

RNG = np.random.default_rng()
table = AnnData(
    X=np.zeros((len(region_column), 1)),
    obs={"region": region_column, "instance_id": instance_id_column},
)
table = table[RNG.permutation(table.obs.index), :].copy()

# Now we have to specify all 3 annotation metadata fields.
sdata_table = TableModel.parse(
    table, region=["blobs_polygons", "blobs_points"], region_key="region", instance_key="instance_id"
)

# When adding the table now, it is validated for presence of annotation targets in the sdata object.
sdata["annotations"] = sdata_table
```
Everything went well so far, but when I input `sdata.set_table_annotates_spatialelement("annotations", region=pd.Series(["blobs_polygons", "blobs_points"]), region_key="region", instance_key="instance_id")`, the following error occurred:

![image](https://github.com/scverse/spatialdata/assets/29703450/857df2ef-3d65-436f-a71b-95a01413d21d)

I can run `sdata.set_table_annotates_spatialelement("table", region="labels_as_circles")` successfully, so I suppose to run `sdata.set_table_annotates_spatialelement("annotations", region=pd.Series(["blobs_polygons", "blobs_points"]), region_key="region", instance_key="instance_id")` successfully, but it failed. Could you help ?

**Comment by wangjiawen2013** [comment]
This is the "obs" of the annotion table:
![image](https://github.com/scverse/spatialdata/assets/29703450/411e2365-8c42-4f7c-a37e-4971c3c6e525)

And this is the 'uns' of the annotation table:
![image](https://github.com/scverse/spatialdata/assets/29703450/7e447344-62be-471e-a250-b912215eb151)

**Comment by melonora** [comment]
Could you give information on which version of spatialdata you are using? I will look into it then:)

**Comment by wangjiawen2013** [comment]
Here are some packages which are related to the issue possibly. I am using python 3.11.6
```
spatial_image                 0.3.0
spatialdata                   0.1.2
spatialdata-io                0.1.2
spatialdata-plot              0.2.2
scanpy                        1.9.6
pandas                        2.1.0
dask                          2024.2.1
dask-image                    2023.8.1
distributed                   2024.2.1
xarray                        2023.11.0
xarray-dataclasses            1.7.0
xarray-datatree               0.0.13
xarray-schema                 0.0.3
xarray-spatial                0.3.7
```

**Comment by melonora** [comment]
Ah I just had a look and the problem is actually quite simple, when specifying the regions you specified also `blobs_polygons` which is not in the `region` column of `obs`, thus you can't specify that the table is annotating this `SpatialElement`.

**Comment by melonora** [comment]
I will set this issue to closed for now, but feel free to ask any question you additionally might have

**Comment by wangjiawen2013** [comment]
blobs_polygons is in the `region` column of `obs` !  You can see that:
![image](https://github.com/scverse/spatialdata/assets/29703450/28795663-7a7f-49a3-9051-7fc54791c1e4)

![image](https://github.com/scverse/spatialdata/assets/29703450/e62de71a-46f9-4a33-937e-16882b86e01f)

**Comment by melonora** [comment]
Ah my apologies I was running from main. I will recheck with the current release version

**Comment by melonora** [comment]
can you try just providing the region as a list instead of series actually so `region=["blobs_polygons", "blobs_points"]`

**Comment by melonora** [comment]
checking against current release now

**Comment by melonora** [comment]
Opening a PR to fix

**Comment by melonora** [comment]
So as stated the next release will be soon so the fix will be soon. Thanks for reporting!
