### ISSUE TITLE
NotImplementedError when converting shape to label

### ISSUE THREAD

**Issue by wangjiawen2013** [scverse/spatialdata#609]
Hi,
This is a chunk of code
```
sdata["rasterized"] = rasterize(
    sdata["blobs_polygons"],
    ["x", "y"],
    min_coordinate=[0, 0],
    max_coordinate=[512, 512],
    target_coordinate_system="global",
    target_unit_to_pixels=1.0,
)
```
When I ran it, the follwoing error occurred ( I am using the latest spatialdata 0.1.2:
![image](https://github.com/scverse/spatialdata/assets/29703450/920442d6-7282-484d-86ec-b2ab3b29a316)

**Comment by melonora** [comment]
Hi @wangjiawen2013 , 

Apologies, we noticed that the doc build is not pointing to current release docs. However, the release will happen this week so you should be able to run this as soon as we cut the release or you can already try from main:)

**Comment by melonora** [comment]
Just FYI the docs now point to the stable version instead of latest from main.
