### ISSUE TITLE
Aggregation notebook is missing output

### ISSUE THREAD

**Issue by ivirshup** [scverse/spatialdata#612]
The aggregation notebook is missing output, currently just shows the code but no results:

https://spatialdata.scverse.org/en/stable/tutorials/notebooks/notebooks/examples/aggregation.html

<img width="1121" alt="image" src="https://github.com/scverse/spatialdata/assets/8238804/c4a39d14-7fa0-4eac-a04b-626b7f79c196">

**Comment by LucaMarconato** [comment]
Thanks for reporting Isaac, at the next release (within 12 hours), the notebook will be fixed.
