### ISSUE TITLE
Support for empty points and empty polygons?

### ISSUE THREAD

**Issue by LucaMarconato** [scverse/spatialdata#62]
Not supporting empty points and empty polygons for the moment.

If we want this, we need to do the following:
- [ ] patch manually the reader and writer for polygons and points since `to_ragged_array()` requires to pass a non-empty `GeoDataFrame`.
- [ ] update `_write_metadata()`: this function expects a tensor shape to be passed in order to write `axes` to NGFF. `axes` is a NGFF 0.4 field that should disappear in NGFF 0.5 (since the axes are included in each coordinate system). So either we wait until `ome-zarr-py` works with 0.5 so we can avoid having to write this field, either we need to be sure that metadata are written correctly (so passing a shape like (0, 3) for a empty list of 3-dimensional points).
But in this second case we would also need to correctly read the axes (so the shape of the points needs to be set manually to (0, 3) if the axes has len 3. But not sure if we can have a empty `GeoDataFrame` object with ndim specified.
- [ ] update `test_roundtrip()` to test point empty points and empty polygons.

**Comment by melonora** [comment]
Together with @LucaMarconato decided not to support this. For tables we also return None in case the table is empty. Furthermore, there is no clear use case for this. Feel free to reopen if someone comes with a usecase.
