### ISSUE TITLE
Import Error: cannot import name '_get_unique_label_values_as_index'

### ISSUE THREAD

**Issue by autumnfe** [scverse/spatialdata#641]
While I was following the tutorial of spatialdata ('Squidy Integration'), I got this error. I couldn't import '_get_unique_label_values_as_index' from 'spatialdata._core.query.relational_query'. 

Is there any solution to resolve it?

**Comment by LucaMarconato** [comment]
Hi, thanks for reporting. Updating the packages of the `spatialdata` ecosystem will fix the issue.
