### ISSUE TITLE
`rasterize_bins()` problem with coordinate transformations and with polygons.

### ISSUE THREAD

**Issue by LucaMarconato** [scverse/spatialdata#650]
I have noticed that `rasterize_bins()` computes the affine matrices on the intrinsic data against the row/col data, ignoring an eventual coordinate transformation. Also it fails when the bins are represented a polygons/multipolygons. I am working on a fix on this, which will solve both problems by calling `get_centroids()`.

- [x] I need to check that performance don't degrade. An ad-hoc solution would be preferred in that case.

CC @quentinblampey

**Comment by quentinblampey** [comment]
Hi luca,
I don't remember all the details, but did we not use `compose_with` in order to handle the coordinate transformations that were set for the bins? Or you're talking about something else?

Great for the polygons/multipolygons!

**Comment by LucaMarconato** [comment]
You are correct, I checked better and the handing of coordinate transformation was right.

In the linked PR I fixed the handing of polygons/multipolygons (using `get_centroids()` is slower than the ad-hoc implementation, so I extended that instead of using `get_centroids()`.
