### ISSUE TITLE
Error on the tutorial Deep learning example on image tiles

### ISSUE THREAD

**Issue by aalia09123** [scverse/spatialdata#652]
Hi,
I have been trying to follow the Deep learning example on image tiles tutorial on the spatialdata scverse website.  However, I keep running into this error : KeyError: 'coords'.
 in the 'Preparing the Data' step. Could I please get some assistance with this?

**Comment by angela18199** [comment]
I am getting the same error when I tried to run this [notebook](https://github.com/scverse/spatialdata-notebooks/blob/main/notebooks/paper_reproducibility/00_xenium_and_visium.ipynb)
When I tried to load data, `landmarks_sdata = sd.read_zarr(LANDMARKS_SDATA_PATH)` 

> ---------------------------------------------------------------------------
> KeyError                                  Traceback (most recent call last)
> Cell In[37], line 4
>       1 bc_sc_atlas_adata = sc.read(BC_SC_ATLAS_PATH)
>       2 bc_sc_atlas_adata.obs["dataset"] = "atlas"
> ----> 4 xe_rep1_sdata = sd.read_zarr(XE_REP1_PATH)
>       5 xe_rep1_adata = xe_rep1_sdata["table"]
>       6 xe_rep1_adata.obs["dataset"] = "xe_rep1"
> 
> File ~/miniconda3/envs/py39_2/lib/python3.9/site-packages/spatialdata/_io/io_zarr.py:121, in read_zarr(store, selection)
>     119     f_elem = group[subgroup_name]
>     120     f_elem_store = os.path.join(f_store_path, f_elem.path)
> --> 121     shapes[subgroup_name] = _read_shapes(f_elem_store)
>     122     count += 1
>     123 logger.debug(f"Found {count} elements in {group}")
> 
> File ~/miniconda3/envs/py39_2/lib/python3.9/site-packages/spatialdata/_io/io_shapes.py:33, in _read_shapes(store, fmt)
>      30 assert isinstance(store, (str, Path))
>      31 f = zarr.open(store, mode="r")
> ---> 33 coords = np.array(f["coords"])
>      34 index = np.array(f["Index"])
>      35 typ = fmt.attrs_from_dict(f.attrs.asdict())
> 
> File ~/miniconda3/envs/py39_2/lib/python3.9/site-packages/zarr/hierarchy.py:511, in Group.__getitem__(self, item)
>     509         raise KeyError(item)
>     510 else:
> --> 511     raise KeyError(item)
> 
> KeyError: 'coords'
> 

I followed all the steps in the notebook and not sure why this doesn't work.

**Comment by LucaMarconato** [comment]
I just made a release for spatialdata, spatialdata-io, napari-spatialdata and spatialdata-plot. The packages should be available via pip within minutes, and should be available in conda earliest in a few hours and latest in 1-2 days.

**Comment by tkcaccia** [comment]
It sounds great. Thank you for your fast reply. Currently, spatialdata is at the version 0.2.1
Are we expecting the version 0.2.2?

**Comment by LucaMarconato** [comment]
Yes, you should be able to install 0.2.2 already from pip: https://pypi.org/project/spatialdata/

**Comment by angela18199** [comment]
Thank you for the fast reply and quick fix!
