### ISSUE TITLE
No matching definition for argument type 

### ISSUE THREAD

**Issue by wangjiawen2013** [scverse/spatialdata#666]
Hi,
When I run sq.gr.nhood_enrichment(sdata["table"], n_jobs=10, cluster_key='id'), the following error occurred:
https://github.com/scverse/squidpy/issues/867

**Comment by LucaMarconato** [comment]
Hi thanks for letting us know. Anyway the bug seems to be `squidpy`-related and not `spatialdata`-related so I will close the current issue, and have the discussion continue in the bug tracked in the `squidpy` repository.
