### ISSUE TITLE
Issue on Deep Learning Tutorial

### ISSUE THREAD

**Issue by aalia09123** [scverse/spatialdata#678]
Hi, I am facing two issues on the 'Deep Learning example on image tiles' tutorial
1) In the from densenet_utils import my_transform
I get the following error ---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[40], line 2
      1 # let's import the above function
----> 2 from densenet_utils import my_transform
      4 dataset = ImageTilesDataset(
      5     sdata=merged,
      6     regions_to_images={"cell_circles": "CytAssist_FFPE_Human_Breast_Cancer_full_image"},
   (...)
     12     rasterize_kwargs={"target_width": 32},
     13 )
     15 dataset[0]

ModuleNotFoundError: No module named 'densenet_utils'

2) while running the code  trainer.fit(model, datamodule=tiles_data_module)
trainer.test(model, datamodule=tiles_data_module) 

I am encountering this issue : RuntimeError: DataLoader worker (pid(s) 21524, 5280, 1216, 20228, 27372, 1380, 24780, 30668) exited unexpectedly

Please advise what to do

**Comment by LucaMarconato** [comment]
Hi, please clone the full `spatialdata-notebooks` repository so that [`densenet_utils.py`](https://github.com/scverse/spatialdata-notebooks/blob/main/notebooks/examples/densenet_utils.py) is discoverable (or alternatively please download that file directly).

The second problem may be a consequence of the first.

**Comment by tkcaccia** [comment]
The code works now I added the following lines. Thank you.

```
import sys
sys.path.append('ADDRESS')

from densenet_utils import my_transform
```

**Comment by LucaMarconato** [comment]
Great to hear! @aalia09123 I will close the issue since I think that the approach used by @tkcaccia would think your issue. But feel free to reopen if you still experience problems.
