### ISSUE TITLE
Improvements to docs

### ISSUE THREAD

**Issue by LucaMarconato** [scverse/spatialdata#69]
@giovp could you please help with these:
- [ ] how to add new elements in APIs? For instance how to add docs for the parsers? (`Image2DModel`, etc)
- [ ] the docs for `SpatialData()` show `Table` for points instead that `pyarrow.Table`. Any way to make clear what is that Table? Unfortunately it seems that the docs for `pyarrow` are not made with Sphynxs, so I didn't manage to make the intersphynx_mapping work

**Comment by giovp** [comment]
yes can set it up this week

**Comment by kevinyamauchi** [comment]
Closing as this has been addressed
