### ISSUE TITLE
The MultiScaleLabel in `blobs` is inconsistent across scales

### ISSUE THREAD

**Issue by timtreis** [scverse/spatialdata#692]
Just noticed that the scales of the `blobs.labels["blobs_multiscale_labels"]` behave weird when visualising:

`sdata_blobs_local.pl.render_labels(label, color="category", table="other_table", scale="scale0").pl.show()`
![image](https://github.com/user-attachments/assets/5eef0562-7a8a-46ac-beb3-0f5799183ba8)

`sdata_blobs_local.pl.render_labels(label, color="category", table="other_table", scale="scale2").pl.show()`
![image](https://github.com/user-attachments/assets/5845d37e-d850-44ef-ad87-f2ab0e31d2f5)

Can be confirmed with
```
import seaborn as sns

fig, ax = plt.subplots(1,1, figsize=(20,20))

sns.heatmap(sdata_blobs.labels["blobs_multiscale_labels"]["scale2"].image.data.compute(), annot=True, ax=ax)
```
![image](https://github.com/user-attachments/assets/5c112061-5856-4ed8-a7aa-39e88ecdae86)

Looks like while downscaling there were some averages computed for the borders so it looks weird now.

CC @LucaMarconato @melonora @Sonja-Stockhaus

**Comment by giovp** [comment]
I think this is possibly related to #697 ,  that is, the default method for resizing doesn't work for labels (bilinear, instead it should be neighbors)

**Comment by LucaMarconato** [comment]
I confirm, the linked PR closes the issue. Full code to reproduce:

```python
import spatialdata
import spatialdata_plot
from spatialdata.datasets import blobs
import matplotlib.pyplot as plt

sdata_blobs_local = blobs()
label = 'blobs_multiscale_labels'

sdata_blobs_local.pl.render_labels(label, color="category", table="other_table", scale="scale2").pl.show()
plt.show()
```
