### ISSUE TITLE
Generating multiscales for labels causes artifacts

### ISSUE THREAD

**Issue by aeisenbarth** [scverse/spatialdata#696]
When parsing a labels element with scale factors, I unconsciously obtained artifacts.

Given a single-scale labels image with unsigned integer dtype and passing `scale_factors`, I assumed SpatialData chooses from the `Labels2DModel` the corresponding scaling method that preserves unique labels (does not introduce new labels as interpolation result from two neighboring labels).

However, it leaves the decision to `to_multiscale`, which defaults to `XARRAY_COARSEN`, same as with normal images.

That means, when passing `scale_factors` to labels, `method` must also be passed explicitly. This seems unintuitive and more users will fall into this trap. I suggest when the class is Image2DLabels / Image3DLabels, we override the default `method`.

```python
import numpy as np
from spatialdata.models import Labels2DModel
from multiscale_spatial_image.to_multiscale.to_multiscale import Methods
import pytest


@pytest.mark.parametrize(
    # "method" not passed, passed as None and passed with "nearest" interpolation
    "method_kwarg", [{}, {"method": None}, {"method": Methods.DASK_IMAGE_NEAREST}]
)
def test_parse_labels_multiscale(method_kwarg):
    # A labels image with one label value 4, that partially covers 2×2 blocks.
    # Downsampling with interpolation would produce values 1, 2, 3, 4.
    array = np.array(
        [[0, 0, 0, 0], [0, 4, 4, 4], [4, 4, 4, 4], [0, 4, 4, 4]], dtype=np.uint16
    )
    actual = Labels2DModel.parse(array, scale_factors=(2,), **method_kwarg)
    assert actual.scale0.image.dtype == array.dtype
    assert actual.scale1.image.dtype == array.dtype
    assert set(np.unique(array)) == set(
        np.unique(actual.scale0.image)
    ), "Scale0 should be preserved"
    assert set(np.unique(array)) >= set(
        np.unique(actual.scale1.image)
    ), "Subsequent scales should not have interpolation artifacts"
```

![issue_labels_multiscales](https://github.com/user-attachments/assets/2867fbb6-479b-407b-9d5f-9e6edf8c9998)

I also was sure the exact same method call was once generating multiscales without artifacts, but I don't know when, and the above example reproduces that there is a problem.

Versions:
- multiscale_spatial_image==1.0.1
- spatial_image==1.1.0
- spatialdata==0.2.2

**Comment by giovp** [comment]
possibly link to #692
