### ISSUE TITLE
Respect xarray coordinates for ImageContainers

### ISSUE THREAD

**Issue by conradfoo** [scverse/spatialdata#723]
**Is your feature request related to a problem? Please describe.**
Currently, if I parse an xarray DataArray into an image container, the coordinates are overwritten with pixel coordinates even if I do not specify a transformation.

**Describe the solution you'd like**
Transfer over the xarray coordinates from the initial xarray into the spatialdata object

**Describe alternatives you've considered**
It is possible (but annoying) to construct a transformation object from my coordinate list and feed that into the constructor.

**Additional context**
I'm using spatialdata-0.2.3
Thanks!

**Comment by LucaMarconato** [comment]
Hi @conradfoo, thanks for reporting.

We actually want to implement this feature. Tracked here https://github.com/scverse/spatialdata/issues/308 (in "there will be a helper function to convert back and forth between BaseTransformation (and so also NGFFBaseTransformation) and xarray coordinates."). I will increase the priority of this feature request.

**Comment by conradfoo** [comment]
Hi Luca, thanks for the quick response! Nice to know it is already being worked on =)

**Comment by conradfoo** [comment]
Closed due to overlap with other feature requests
