### ISSUE TITLE
Dask dataframe vs Polars

### ISSUE THREAD

**Issue by gouinK** [scverse/spatialdata#731]
More of a design question, I am curious to hear the tradeoffs between using [Dask](https://docs.dask.org/en/stable/dataframe.html) dataframes vs [geopandas](https://geopandas.org/en/stable/) vs [Polars](https://pola.rs/) for [Points](https://spatialdata.scverse.org/en/latest/generated/spatialdata.models.PointsModel.html)? I have been migrating my heavy workflows to Polars, but am also interested in potentially utilizing SpatialData, so I wanted to consider what the tradeoffs might be.

Thanks!

**Comment by melonora** [comment]
@LucaMarconato perhaps you can say more about the design decision initially for dask and add to anything I say.

For Polars, as far as I know Polars is meant to be single machine while this is not the case for dask. Dask also follows more the pandas API which most people are more familiar with and although Polars is catching up integrates better with other libraries in the Python ecosystem.

With regards to geopandas, of course this provides the geospatial tooling which dask does not provide (although dask geopandas does look interesting), while geopandas again is single machine.

**Comment by melonora** [comment]
Closing this for now but feel free to reopen if you feel like your question was not sufficiently answered.
