### ISSUE TITLE
Improving ergonomics for channel names handling

### ISSUE THREAD

**Issue by LucaMarconato** [scverse/spatialdata#750]
Brainstormed together with @minhtien-trinh. 

Working with channel names in multi-channel images in not straightforward. In particular:
- [x] the `c_coords` argument in `Image2DModel.parse()` is too hidden; we should move it out of `kwargs`
- [ ] we could consider adding an helper function `set_channels()` (to complement `get_channels()`)
- [ ] `SpatialData.write_metadata()` currently doesn't handle channel names, so it is not possible to easily overwrite the channel names metadata without rewriting the heavy raster data.

**Comment by melonora** [comment]
just waiting for review @minhtien-trinh

**Comment by minhtien-trinh** [comment]
Looks great to me, thank you for handling this @melonora
