### ISSUE TITLE
3D image order axes constraint breaks io

### ISSUE THREAD

**Issue by LucaMarconato** [scverse/spatialdata#84]
Discovered by @berombau when converting the MERSCOPE dataset.

The function `to_multiscale` from `spatial-image`, requires the `zyxc` order. At the moment this break io. I think @giovp is already aware of the problem.

**Comment by giovp** [comment]
yes indeed, this is something might be better to address upstream.

**Comment by kevinyamauchi** [comment]
Do we need to make a patch here to unblock us while we make the upstream fix or can this wait?

**Comment by LucaMarconato** [comment]
I would also try to address it upstream because we can still work on the other datasets, but I wanted to remerge the awareness of this limitation so we can focus on it sometimes soon.
