### ISSUE TITLE
repr has extra arm in the last line of the tree

### ISSUE THREAD

**Issue by kevinyamauchi** [scverse/spatialdata#89]
the last line in the repr has an extra "arm" in the last line of the tree:

<img width="780" alt="Screenshot 2022-12-15 at 14 16 54" src="https://user-images.githubusercontent.com/1120672/207978988-6383a0d5-ec01-48af-bff4-ac9633d296d9.png">

**Comment by kevinyamauchi** [comment]
I believe this is because the current repr assumes the last element is a table.

https://github.com/scverse/spatialdata/blob/8e92382f42110c8380269ba70ae1d9dd8a346e8f/spatialdata/_core/_spatialdata.py#L316-L319

**Comment by LucaMarconato** [comment]
Ooooh thanks!
