### ISSUE TITLE
mypy installation fails

### ISSUE THREAD

**Issue by LucaMarconato** [scverse/spatialdata#94]
Mypy checks pass offline, but the github action fails because the env can't be found.
I'll still merge two prs that have been approved to main, the red mark being due to this issue.
<img width="794" alt="Screenshot 2023-01-04 at 17 15 17" src="https://user-images.githubusercontent.com/2664412/210600204-f8a34648-3d08-4740-a323-55a29c582afc.png">

**Comment by ivirshup** [comment]
@LucaMarconato it looks like it's just timing out. It seems odd to me that *just installation* would time out.

I can't replicate installation taking anywhere near as long on my machine, so couldn't guess what's up.

Re your comment on zulip, not clear to me that this is mypy, I think we're only seeing a few lines of the log.

**Comment by ivirshup** [comment]
Hmm, maybe the log is meant to be mypy specific? Not sure how pre-commit ci actually runs. If it's mypy we could just move mypy out to a separate CI action, since I don't think it would ever modify the code itself – the main benefit of the pre-commit CI service.

**Comment by LucaMarconato** [comment]
Thanks, I removed mypy from the CI [as shown here](https://github.com/pre-commit-ci/issues/issues/53). I also had to update the link to the badge because it was broken. Now it seems to work.

**Comment by LucaMarconato** [comment]
Maybe the changes could be included in the cookie cutter. Not sure why the url of the badge changed.
