### ISSUE TITLE
allow image models to parse list of images and transforms

### ISSUE THREAD

**Issue by giovp** [scverse/spatialdata#96]
https://github.com/scverse/spatialdata/blob/419c7b61c7358344e1d4052262111f0d5f51890c/spatialdata/_core/models.py#L169

**Comment by LucaMarconato** [comment]
Parsing multiple transformations is now supported by https://github.com/scverse/spatialdata/pull/100.
I would not allow for passing multiple images (to construct a `MultiscaleSpatialImage`) as discussed here: https://github.com/scverse/spatialdata-io/issues/15.

In fact I would always start from a large image and let `to_multiscale()` create the subresolutions.

I close, please reopen if you think that we still need to support that.
