### ISSUE TITLE
function to determine what type of element an object is 

### ISSUE THREAD

**Issue by kevinyamauchi** [scverse/spatialdata#98]
As described [here](https://github.com/scverse/spatialdata/pull/93#issuecomment-1368248419), it would be nice to have a helper function that determines what type of element a given object is.

**Comment by LucaMarconato** [comment]
I needed this for the new transforms branch so I added it. The function is called `get_schema()` from `models.py`. This is the signature:

```
SpatialElement = Union[SpatialImage, MultiscaleSpatialImage, GeoDataFrame, AnnData, pa.Table]
Schema_t = Union[
    Image2DModel, Image3DModel, Labels2DModel, Labels3DModel, PointsModel, PolygonsModel, ShapesModel, TableModel
]


def get_schema(
    e: SpatialElement,
) -> Schema_t:
```

**Comment by LucaMarconato** [comment]
It's has been renamed to `get_model()`.
